/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Requires:": "要求：",
    "RESET": "重置",
    "RESET TALENTS": "重置天赋",
    "resour": "资源",
    "SIGN": "符号",
    "Skills": "技能",
    "SOLD OUT": "售罄",
    "Started On:": "开始于：",
    "Super Turtle Idle": "超级乌龟放置",
    "Stern Cricket": "斯特恩板球",
    "Upgrades": "升级",
    "Unlock": "解锁",
    "Upgrades Unlocked": "已解锁升级",
    "Turtle Coins": "乌龟金币",
    "Travel": "旅行",
    "Township": "乡镇",
    "Total Kills:": "总计击杀：",
    "Total Defeats:": "总计失败次数：",
    "Total Boss Kills:": "总计Boss击杀：",
    "Time Magic": "时间魔法",
    "This action is": "这个动作",
    "Thank you for enrolling in the Super Turtle Adventure program!": "感谢您参加超级乌龟冒险计划！",
    "This is basically a beta test": "这基本上是一个 Beta 测试",
    "Treaties allow the potential of your turtle empire to reach new heights by focusing on specific elements of your kingdom.": "通过专注于王国的特定元素，条约可以让您的乌龟帝国的潜力达到新的高度。",
    "VERSION HISTORY": "版本记录",
    "Wishing Stars": "许愿星",
    "time skipped:": "跳过的时间：",
    "Shop": "商店",
    "Revive": "复活",
    "DELETE": "删除",
    "DROPS": "掉落",
    "Equipment": "装备",
    "Fishing": "钓鱼",
    "Forgotten Series": "失落物系列",
    "Foraging": "采集",
    "Gold-Tinged Gamba": "鎏金大虾",
    "God": "神明",
    "Honor Shop": "荣誉商店",
    "Hallow Forest": "神圣森林",
    "Import Save": "导入存档",
    "Guildwork": "公会工作",
    "GAME OPTIONS": "游戏选项",
    "Important Notice": "重要通知",
    "Dai-Goran": "戴戈兰",
    "Dayleaf Spice": "日桂香料",
    "REDEEM": "领取",
    "saved data?": "保存的数据？",
    "SKILLS": "技能",
    "SOON": "很快",
    "Turtle Clicks made:": "乌龟点击：",
    "You obtain": "你得到了",
    "Total Coins Gained:": "获得的金币总数：",
    "Total Playtime:": "总游戏时长：",
    "We are appreciative of your participation in our program. Turtles all across the world will be happy rely on your help and will reward you handsomely for your bravery!": "我们非常感谢您参与我们的计划。 世界各地的海龟都会很高兴依靠你的帮助，并会因为你的勇敢而丰厚地奖励你！",
    "recipes": "配方",
    "We sincerely hope you continue with our program and have a wonderful journey! Here is a welcome gift:": "我们真诚地希望您继续我们的计划并祝您旅途愉快！ 这是一份欢迎礼物：",
    "When the Astral gauge completes, you can get access to the": "当星体量表完成后，您可以访问",
    "When you sign a treaty, a set of": "当您签署条约时，会出现一系列",
    "will be born in honor of your dynasty, alongside increased": "将为您的王朝而诞生，同时增加",
    "You can only switch treaty after an hour.": "您只能在一小时后更改条约。",
    "You will step down from your position as leader of the turtles, and three": "你将从海龟领袖的位置上退下来，并且三个",
    "Your": "你的",
    "Your hard working Penguin Helpers have been working for you while you weren't online for": "在您离线时，辛勤的企鹅助手一直在为您工作",
    "⚠ Sell Mode ⚠": "⚠ 出售模式 ⚠",
    "⚠ Lock Mode ⚠": "⚠ 锁定模式 ⚠",
    "⚠ Favorite Mode ⚠": "⚠ 收藏模式 ⚠",
    "❖ Fleming Bite: Applies poison on attack.": "❖ 蜇伤: 在攻击时施放毒药。",
    ", and": ", 并",
    ", you can spend the": "，您可以花费",
    "(click anywhere to close)": "（点击任意一处关闭）",
    "<No Class>": "<无职业>",
    "all": "全部",
    "and": "和",
    "and will": "并将",
    "Armory": "军械库",
    "coins": "金币",
    "exp!": "经验值!",
    "Inventory": "仓库",
    "Jester Turtles Clicked:": "小丑龟点击次数：",
    "Kill": "击杀",
    "MAILBOX": "邮箱",
    "Money": "钱",
    ". Furthermore, treaties can be ranked up to further boost their effects.": "。 此外，可以对条约进行排名，以进一步增强其效果。",
    "\"texto texto texto texto texto texto texto texto texto texto texto\"": "\“文字文字文字文字...",
    "(click outside this window to close)": "（点击该窗口外区域即可关闭）",
    "(Full Changelog in the Discord Server)": "（Discord 服务器中的完整更新日志）",
    "[Left Click] Sell One | [Right Click] Sell All": "[左键]出售一个| [右键]出售所有",
    "[Left Click] to Add to the Favorite Tab": "[左键点击]添加到收藏标签",
    "[Left Click] to Prevent Items From Being Sold": "[左键点击]防止物品被出售",
    "A big thank you for everyone willing to support the development of the game!": "非常感谢大家愿意支持游戏的开发！",
    "A slug so passionate about vegetables that he raised one on its shell. Scientists are in absolute awe.": "一只蛞蝓对蔬菜非常热衷，以至于他在壳上养了一个。 科学家们感到无比敬畏。",
    "Achieve": "达成",
    "Active": "活跃",
    "Active Playtime:": "活跃游戏时长：",
    "Added a bunch of stats for nerds": "为书呆子添加了一堆统计数据",
    "Added and then reworked the achievement system": "添加并重新设计了成就系统",
    "Added Classes and Skills": "添加了课程和技能",
    "Added Crit Chance": "添加暴击几率",
    "Added day cycles and a weather system (not very used for now)": "添加了日循环和天气系统（目前不太使用）",
    "Added Dungeons": "添加了地下城",
    "Added Fishing": "添加了钓鱼",
    "Added Garrisons": "添加驻军",
    "Added import and export save functionality": "添加导入导出保存功能",
    "Added Insight": "添加洞察",
    "Added Jester Turtles": "添加小丑龟",
    "Added Mail": "添加邮件",
    "Added Mystery Presents": "添加神秘礼物",
    "Added Penguin Helpers, Penguin power, and other penguin nonsense": "添加了企鹅助手、企鹅力量和其他企鹅废话",
    "Added professions": "添加职业",
    "Added SFX": "添加特效",
    "Added Stamps": "添加图章",
    "Added the Collection and the Armory": "添加收集品和军械库",
    "Added the first two areas (acting as some sort of tutorial)": "添加了前两个区域（作为教程）",
    "Added the rpg maingame": "添加了RPG主游戏",
    "Added three new areas, hundreds of items, achievements, yada yada": "添加了三个新区域，数百个物品，成就等等",
    "akerson": "阿克森",
    "All your Talent Points will be refunded.": "您的所有天赋点都将被返还。",
    "Alone No More": "不再孤单",
    "Arcanum Liber": "自由奥秘",
    "are slowly filling up the": "正在慢慢填满",
    "Are you sure you want to delete": "你确定你要删除",
    "Astral gauge": "星体规",
    "Astral level": "星体等级",
    "Banish": "放逐",
    "Beastfallen Series": "堕兽者系列",
    "billyawn": "比利翁",
    "Blood Magic": "血魔法",
    "Blue Magic": "青魔法",
    "boons and banes will apply": "祸福相依",
    "Camp Construction": "营地建设",
    "Caulislug recieves": "卷心蛞蝓接收",
    "Chai Chai Real Smooth": "茶茶口感顺滑",
    "Coins Produced by Clicking:": "点击产生的硬币：",
    "Collection": "收集品",
    "Combat Log": "战斗日志",
    "Combat Statistics": "战斗统计",
    "Common": "常见",
    "Constellations": "星座",
    "Copper Plate": "铜板",
    "Cradle Hills": "摇篮山丘",
    "Craft": "工艺",
    "Creates:": "创建：",
    "delete all progress of the game": "删除所有游戏进度",
    "DELETE DATA": "删除数据",
    "DELETE SAVEDATA": "删除存档",
    "DESCRIPTION": "描述",
    "Dreamwoven Gamba": "织梦大虾",
    "Dungeons Cleared:": "已清理地牢：",
    "energy": "活力",
    "Exploration": "探索",
    "Export Save": "导出保存",
    "food": "食物",
    "for the next": "为下一个",
    "Garrison": "驻军",
    "Garrison Supplies": "驻军补给",
    "General": "常规",
    "Gladiator Rank to unlock": "角斗士等级后解锁",
    "Grand Archive": "大档案馆",
    "Granite Grotto": "花岗岩窟",
    "Have You Seen My Pet": "您看到我的宠物了吗",
    "heinrich1960": "海因里希1960",
    "Heirloom Series": "传家宝系列",
    "horas\n       ": "时间\n",
    "huskymudkipper56": "哈士奇鲈鱼56",
    "in perks to carry over your next legacy.": "获得继承下一个遗产的福利。",
    "In that time, they managed to collect": "在那段时间，他们设法收集",
    "Insight Gained :": "获得的洞察：",
    "invisibilia_draconis": "隐形龙",
    "irreversible": "是不可逆的",
    "Item Of The Day": "今日特价",
    "Items Crafted:": "已制作物品：",
    "Items Sold:": "已售出物品：",
    "Items Stolen:": "已偷窃物品：",
    "Last Time: Undefeated": "最佳用时：未击败",
    "Last Wave: Unattempted": "最多波次：未尝试",
    "leave behind all activities, upgrades, coins, resources and exploration levels": "留下所有活动、升级、金币、资源和探索级别",
    "Lesser Alchemical Dust": "小份炼金粉尘",
    "LEVEL": "等级",
    "LOCKED": "锁定",
    "Lost Dojo": "世外道场",
    "Lumberjack Post": "伐木工人驿站",
    "Lush Passageway": "郁郁葱葱的通道",
    "Made by \"duck\" [drvcx] 🦆": "由“鸭子”[drvcx] 🦆 制作",
    "Make every effort to assist your fellow turtles, as the adventure guild will bestow upon you a unique reward when you fulfill all of their requests in a given area.": "尽一切努力帮助你的海龟同伴，因为当你在特定区域满足他们的所有要求时，冒险公会将给予你独特的奖励。",
    "Masterwork Series": "杰作系列",
    "Metal Workshop": "金属作坊",
    "Millionaire Series": "百万富翁系列",
    "Miners Guild Request": "矿工公会委托",
    "Monster Arena": "怪物竞技场",
    "Mystery Presents Opened:": "神秘礼物开启：",
    "Mystery Tickets": "神秘门票",
    "Nameoftheturtle": "乌龟的名字",
    "NEXT ASTRAL LEVEL:": "下一个星体层：",
    "Next Shop Restock": "店铺补货倒计时",
    "Next Talent Point:": "离下个天赋点还有：",
    "Novice Alchemy Recipes": "新手炼金术配方",
    "Novice Blacksmith": "新手铁匠",
    "Novice Blacksmith Recipes": "新手铁匠配方",
    "Novice Cooking Recipes": "新手烹饪配方",
    "Novice Engineering Recipes": "新手工程配方",
    "Oh god what did i do": "天啊我做了什么",
    "On the": "上",
    "Overhauled the graphical aspect of the game... again": "再次彻底修改了游戏的图形方面",
    "Patreon Supporters": "Patreon支持者",
    "penguin": "企鹅",
    "Penguin Assistants": "企鹅助手",
    "Penguin Glacier": "企鹅冰川",
    "Performance": "表现",
    "Pirate Galleon": "海盗帆船",
    "Planetarium": "天文馆",
    "Quests Completed:": "已完成任务：",
    "Epicardo Item": "艾皮卡多物品",
    "Relics": "遗物",
    "Remade everything": "重做一切",
    "Removed max item limit": "移除了物品最大数量限制",
    "Rename your turtle!": "给您的乌龟重新命名！",
    "Request From a Toad": "蟾蜍的委托",
    "Requires Novice Blacksmith [0]": "需要 新手铁匠 [0]",
    "Research Facility": "研究设施",
    "Revamped the entire graphical aspect of the game": "改进了游戏的整个图形方面",
    "Revered Series": "尊崇系列",
    "Royal Pudding": "皇家布丁",
    "Sawmill Plant": "锯木厂",
    "Slug Meat": "蛞蝓肉",
    "Smelt ore into an ingot of copper.": "将矿石熔炼成铜锭。",
    "Solstice Series": "至日系列",
    "Stamp Weapon": "印记武器",
    "Support the game ❤️": "支持游戏❤️",
    "Support The Game!": "支持游戏！",
    "texto texto texto texto texto texto texto texto texto texto texto": "文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字",
    "This operation will consume one": "此操作会消耗一个",
    "To My Beloved Friend": "致我挚爱的朋友",
    "Trial of the Mountain": "山之试炼",
    "Uncommon": "罕见",
    "“ I am a prince from Nigeria and a giant idiot spider destroyed shop, give me your money please.": "“我是尼日利亚的王子，一只又大又蠢的蜘蛛毁了我的店面，请给我一些钱。",
    "“ Muggey, the president of the Chai Association, requests to see the most unusual chai blend of the lands.": "“ 茶协会主席马吉 (Muggey) 要求观赏这片土地上最少见的混合香料茶。",
    "“ My pet Hoopperoona has gone missing. You will recognise her for her eight legs, rocky skin, and the ability to melt steel beams with her saliva.": "“我的宠物胡佩罗娜失踪了。 她有八条腿、岩石般坚硬的皮肤，还能用唾液熔化钢梁，您一眼就能认出她。",
    "“ Ribbit Ribbit. Ribbit Ribbit Ribbit Ribbit Ribbit Ribbit Ribbit.  Ribbit Ribbit.": "” 呱呱。 呱呱呱呱呱呱呱。呱呱。",
    "“ These scorpions keep blocking the road to our sweet, sweet rocks. Clear the road and well show you our rocky goodness.": "“这群蝎子挡住了我们甜蜜岩石乡的归途。 清理障碍，我们将向您展示岩石的善良。",
    "“ To complete the registation of the Super Turtle Adventure program, please terrorise the local wildlife.": "“为了完成超级海龟冒险计划的注册，请恐吓当地的野生动物。",
    "\"Life is like a Small Wooden Lockbox.\"": "“人生就像是一个上锁的小木箱。”",
    "\"Seems inedible, but probably a delicatessen in some parts of France.\"": "“难以入口，在法国的某些地方却是珍馐。”",
    "\"This is going to be a terrible night...\"": "“这将是一个可怕的夜晚……”",
    "\"This one is just a rusty sword.\"": "“只是一把生锈的剑。”",
    "[Possible Contents]": "[可能的内容]",
    "[Tip: Gear levels up automatically after getting multiple copies. Try buying multiple of them] ”": "[提示：获得多个相同装备，它会自动升阶。 尝试在商店购入装备]”",
    "[Tip: You can click the turtle to get coins] ”": "【提示：点击乌龟即可获得金币】”",
    "[Tip: You can equip gear by right-clicking it] ”": "【提示：右键点击可以穿戴装备】”",
    "[Tip: You can sell items by pressing Control] ”": "【提示：按住Control键以出售物品】”",
    "[Tip: You can switch browser tabs while the game is running] ”": "【提示：游戏运行时浏览器可以切换至其他页面】”",
    "[Tip: You might want to come later to do certain quests] ”": "[提示：你可以稍后再来完成某些任务]”",
    "{texto texto texto texto texto texto texto texto texto texto texto}": "{文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本",
    "❖ ...And More!": "❖ ...以及更多！",
    "❖ Defeat 50 Ribulls": "❖ 击败 50 牛呱",
    "❖ Defeat 50 Stinglets": "❖ 击败 50 小蜇蝎",
    "❖ Defeat a bunch of slugs": "❖ 击败一群蛞蝓",
    "❖ Defeat Hoopperoona": "❖ 击败 胡佩罗娜",
    "❖ Foliar Blade": "❖ 叶刃",
    "❖ Hand over 2500 Turtle Coins": "❖ 递交 2500 枚海龟币",
    "❖ Malachite": "❖ 孔雀石",
    "❖ Nephrite": "❖ 闪玉",
    "❖ Pine Boomerang": "❖ 松木回旋镖",
    "❖ Recipe: Nephrite-Embedded Ring": "❖ 配方：镶玉戒指",
    "❖ Recipe: Net-o-Launcher 3000": "❖ 配方：捕网器 3000",
    "❖ Right Click to add to your collection": "❖ 右键单击添加物品到您的收藏中",
    "❖ Show an unusual tea blend to Muggey": "❖ 向马吉展示一种少见的混合香料茶",
    "❖ Skewed Lizard": "❖ 斜蜥蜴",
    "❖ Thorn Binding": "❖ 荆棘束缚",
    "❖ Wooden Stamper": "❖ 木制图章",
    "A cool stick": "很酷的棒子",
    "Access to the Shop": "进入商店",
    "Can be used to summon Hoopperoona": "可以用来召唤胡佩罗娜",
    "Collectible": "收集品",
    "Consumable - Container": "消耗品 - 容器",
    "Experience": "经验",
    "Material": "材料",
    "Miscellaneous": "杂项",
    "Miscellaneous - Collectible": "杂项 - 收集品",
    "Not Collected": "未收集",
    "Objective:": "目标：",
    "Pointy Relic": "尖尖的遗物",
    "Reality Voxel": "现实体素",
    "Masala Chai": "玛莎拉茶",
    "Rewards:": "奖励：",
    "Ribbit Ribbit Ribbit": "呱 呱 呱",
    "Sell value:": "售价：",
    "Small Wooden Lockbox": "上锁的小木箱",
    "Trapped Cage": "陷阱牢笼",
    "Turtle Voice by \"lily\" [.lilynee] 🐑": "海龟之声 by \"lily\" [.lilynee] 🐑",
    "Unlock Ore Node": "解锁矿石节点",
    "Unlock with a Copper Key to open": "使用铜钥匙解锁",
    "Game Saved": "游戏已保存",
    "(Unique)": "(未装备)",
    "\"A wooden stick shaped like a sword, retaining all the properties of a wooden stick and none of a sword.\"": "“一柄削成剑形的木棍，保留了木棍的所有属性，唯独没有剑的属性。”",
    "COMPLETED": "已完成",
    "Equipable - Weapon": "可装备-武器",
    "Poor": "粗劣",
    "Wooden Sword": "木剑",
    "\"The birds are singing, flowers are blooming, on days like these, turtles like you, should have a good day.\"": "“小鸟在歌唱，鲜花在绽放，在这样的一天里，像你这样的乌龟，应当在阳光中微笑。”",
    "Click to cycle through tips": "单击可循环浏览提示",
    "Dedicated Drops": "专属掉落",
    "Enemy": "敌人",
    "No special weather bonuses.": "无特殊天气奖励。",
    "Press to fight a meddlesome foe": "按下以对抗容易的敌人",
    "Press to fight a troublesome foe": "按下以对抗棘手的敌人",
    "Press to summon the boss of this area": "按下以召唤该区域的boss",
    "Requires [Trapped Cage] x1": "需要[陷阱牢笼] x1",
    "Sunny Day": "晴天",
    "There is no limit of how many items you can have on the inventory (at least i didnt code one...!)": "仓库中可以拥有的物品数量没有限制（至少我没有编码......！）",
    "Weather": "天气",
    "\"A wooden badge commemorating your initiation into adventuring.\"": "“一枚纪念你初出茅庐的木质徽章。”",
    "Adventurer Badge": "冒险家徽章",
    "Does nothing ...Or does it?": "一文不值……也许不是?",
    "Equipable - Trinket": "装备-饰品",
    "Make every effort to assist your fellow turtles whenever you go.": "无论你去哪里，都要尽一切努力帮助你的海龟同伴。",
    "We are appreciative of your participation in our program. Turtles all across the world will be happy to rely on your help and in exchange we will reward you handsomely for your bravery!": "我们非常感谢您参加我们的节目。全世界的海龟都很乐意依靠您的帮助，作为交换，我们会对你的勇敢奉上丰厚的奖励!",
    "We sincerely hope you continue with our program and have a wonderful journey! Here is your welcome badge:": "我们真诚地希望您继续参与我们的节目，并有一段美好的旅程!这是给您的欢迎徽章:",
    "Wood-Carved Gamba": "木雕大虾",
    "Collected!": "已收集！",
    "Press to fight a frightsome foe": "按下以对抗可怕的敌人",
    "\"Ancient construct that somehow always points out in the same direction.\"": "“古老的建筑，不知何故总是指着同一个方向。”",
    "Guiding Relic": "指引遗物",
    "Mystery Present": "神秘礼物",
    "Mystery Present recieves": "收到神秘礼物",
    "Collected": "已收集",
    "Calm Night": "宁静之夜",
    "\"Its oddly calm tonight.\"": "“今晚出奇地平静。”",
    "permanently": "永久性的",
    "CLICK BOOST!": "点击提升!",
    "Inactive": "非活跃",
    "\"A vital reagent in alchemy and the cauldrons of every self-respecting witch.\"": "“在炼金术和每位体面女巫的坩埚中必不可少的一味药。”",
    "\"One export save a day keeps the data corruption away.\"": "“每天导出档，丢档远离我。”",
    "Carefully Wrapped Exported Data": "精心包装的导出存档",
    "Consumable - Miscellaneous": "消耗品-杂项",
    "Frog Leg": "青蛙腿",
    "Open it!": "打开它!",
    "Recognized for their loud croaking sound, numerous noise complaints have been filled wherever they reside. But they never listen...": "它们以响亮的蛙鸣声而闻名，无论住在哪里，都会收到无数的噪音投诉。但它们完全不听……",
    "\"...Encased within the shell of the cosmic ovum lay the potential for eternity, awaiting the pivotal moment of hatching, as within resided...\"": "\”…宇宙之卵的壳里潜藏着永恒，静候孵化的那一刻，正如生命伊始……”",
    "\"The fast pass of the adventures.\"": "“冒险的快速通行证。”",
    "(Only works if the current enemy has been defeated more than 100 times)": "(仅在击败当前敌人超过100次时生效)",
    "Can be used to enter any dungeon": "可以用来进入任何地牢",
    "Dungeon Voucher": "地牢凭证",
    "Epic": "史诗",
    "Perennial Time Egg": "永恒之蛋",
    "Rare": "稀有",
    "Fast-forwards 6 hours of offline progress": "快进6小时的离线进度",
    "An overgrown arachnid that doesn't seem too up for conversation.": "一只体型巨大的蛛形动物，看起来不太愿意交谈。",
    "It is said that the poison of these scorpids is more lethal the whiter their tails are. It also kinda looks like a baguette.": "据说，这些蝎子的尾巴越是白，毒液就越是致命。不过看起来倒是有点像法棍。",
    "When you level up, your Strength, Max Health and Regeneration go up.": "当你升级的时候，你的力量，最大生命值和回复都会得到提升。",
    "Area bosses are a great source of experience.": "区域Boss是绝佳的经验来源。",
    "Attributes marked with": "标记的属性",
    "Complete missions to recieve useful rewards in the mail.": "完成任务可以从邮件中收到有用的奖励。",
    "Defeating low-level enemies can yield more materials and money at the expense of experience.": "击败低级敌人经验值较少但获得的材料和金钱相对更多。",
    "Drops marked with a ★ are rare and wont be increased by the Drop Chance stat.": "标有★的掉落物是罕见的，不会受掉落倍率影响。",
    "Gear marked as \"Unique\" will level up with multiple copies of itself, but only if they have a roman numeral at the side of their name.": "标记为“唯一”的装备可借助相同的装备升级，但前提是装备的名字旁有罗马数字。",
    "have unusually high upgrade scaling.": "具有相当高的升级提升。",
    "Hold Control to sell your items.": "按住Control键以出售物品。",
    "Is the enemy too hard? Be sure to check its description and skills to fight accordingly.": "敌人太强打不过?仔细观察敌人描述和技能来针对性地战斗。",
    "The materials found in chests scale with your progress, so be sure to always open them for easy drops.": "箱子里开出的材料将随着你的进度增加，记得时常开箱来获取掉落物。",
    "You can buy multiple items at once in the shop by pressing Control.": "你可以在商店里按住Control键一次购买数个物品。",
    "Upgrade": "升级",
    "Price:": "价格:",
    "\"A fine sword bestowed to the nobility of the turtle kingdom. They say that blood spilled with this edge bleeds blue.\"": "“一柄赐予龟国贵族的好剑。据说，剑刃挥下，流出的血是蓝色的。”",
    "\"A foul-smelling rag for the forehead. Unfortunately, it goes in the head slot.\"": "“一块难闻的破布。很不幸，你得把它戴在头上。”",
    "\"An ordinary jewelry ring. You can sense good craftsmanship out of it.\"": "“一枚寻常的珠宝戒指。蕴含了精湛的工艺。”",
    "\"Don't complain, it tastes like chicken.\"": "“别抱怨了，它尝起来像鸡肉。”",
    "\"For the easily-influenced locks.\"": "“专为易受影响的锁设计。”",
    "\"It should hold together for a few shots before falling apart entirely.\"": "“在完全散架之前，应该还能射几箭。”",
    "\"May contain beans.\"": "“可能装了豆子。”",
    "\"Might be useful in a pinch.\"": "“在危机关头也许能派上用场。”",
    "\"More effective than nothing whatsoever. Not much more, though.\"": "“总好过什么都不穿。不过也差不了多少。”",
    "\"Seems to not be of your size.\"": "“好像不合你的尺寸。”",
    "\"The key to a massive library recording specifics about the past, present, and future.\"": "“用于开启一个记录过去、现在和未来详情的庞大图书馆的钥匙。”",
    "\"The kind your turtle grandmother would wear.\"": "“你的乌龟祖母会穿的那种。”",
    "\"They must at least be resistant if they were able to survive this long.\"": "“活了这么长时间，这条裤子至少是挺耐穿的。”",
    "\"Three thousand years ago, this baby would be considered top-notch engineering, but right now it's better than punching rocks.\"": "“假设回到三千年前，这个小玩意会是一流的工程设计，但放到现在它只比拳击石头要好一些。”",
    "\"Truth is... the game was rigged from the start.\"": "\“其实……游戏从一开始就被动了手脚。”",
    "\"Warm and fuzzy pats are guaranteed by the soft fur of the gloves\"": "“手套柔软的皮毛带来温暖和毛茸茸的拍拍。”",
    "Can be used to gather ores and herbs": "可以用来采集矿石和草药",
    "Can open small containers": "能打开上锁的小木箱",
    "Cloth Set:": "破布套装:",
    "+7% Item Drop Chance": "增加7%物品掉落倍率",
    "Might Damage": "力量伤害",
    "Low chance to inflict a royal slash dealing 150-200": "低几率使出皇家劈砍，造成150-200点",
    "Shoot a wooden arrow": "射出一支木箭",
    "Shoot a wooden arrow'": "射出木箭",
    "Permanently increases Turtle Coin reward from clicking by +40": "永久增加点击龟币奖励+40",
    "Permanently unlocks the Grand Archive, gaining insight as you collect books on it": "永久解锁大档案馆，当你收集到书籍时获得洞察",
    "Prevents enemy-inflicted poisons for 10 minutes": "防止被敌人施加毒药，持续10分钟",
    "Restores 1500-2000 Health": "恢复1500-2000点生命值",
    "Pay 2 Win": "氪金",
    "'pat pat pat pat pat pat pat pat pat'": "\"拍，拍，拍，拍，拍\"",
    "\"... all five pieces of the puzzle!\"": "\”…五个拼图碎片集齐了!\”",
    "\"...........my mone.\"": "\"...........我的钅。\”",
    "\"A clump of impure copper ore. For such crude ore to be helpful, it must undergo extensive refinement.\"": "“一块含杂质的铜矿石。要使用这种粗矿石，必须进行大量的提炼。”",
    "\"An elvish weapon used by the forest dwelling race known as the Australians.\"": "“森林种族澳大利亚人使用的一种精灵武器。”",
    "\"An impure variety of jade. Despite that, it still can fetch a good price.\"": "“一种含杂质的玉。尽管如此，它仍然可以卖个好价钱。”",
    "\"And this... Is to go further beyond.\"": "\”而这……是更远的一步。”",
    "\"Best I can do is 200 Coins.\"": "“我最多只能出200个金币。”",
    "\"Break a leg.\"": "“祝你好运。”",
    "\"Do you have the client card?\"": "“你有会员卡吗?”\”",
    "\"Everyone is invited c:\"": "“每个人都被邀请了c:\”",
    "\"Feels good man.\"": "“感觉不错吧，伙计。”",
    "\"First of many.\"": "“这是第一步。”",
    "\"Gacha? Gacha? Gacha!\"": "\“抽卡?抽卡吗?抽卡!\”",
    "\"Gameplay.\"": "\"游戏玩法。\”",
    "\"Give the cat what he wants.\"": "“给猫它想要的。”",
    "\"Glad we sorted this out one with words alone.\"": "“很高兴我们只用文字就解决了这个问题。”",
    "\"Gotta study them all.\"": "“要把它们都研究一遍。”",
    "\"I could tell you a thing or two.\"": "“我可以为你解答一二。”",
    "\"I got enough points for the pot set.\"": "“我有足够的点数来换那套锅了。”",
    "\"I love the smell of gunpowder in the morning.\"": "“我喜欢清晨的火药味。”",
    "\"I really was ready.\"": "“我真的准备好了。”",
    "\"I saw you peeking.\"": "“我看见你偷看了。”",
    "\"I'm Ready! I'm Ready! I'm Ready! I'm Ready!\"": "\“我准备好了!我准备好了!我准备好了!我准备好了!\”",
    "\"If I can't get them, no one will.\"": "“我得不到的，其他人也别想。”",
    "\"It just doesn't feel morally right, right?\"": "“这在道德上是不对的，对吧?”\”",
    "\"It seems she took a liking to you.\"": "“看来她喜欢上你了。”",
    "\"Let your voice be heard.\"": "“听听您的意见。”",
    "\"Literally speaking, that is.\"": "“实际上正是如此。”",
    "\"Look it up, its a real word.\"": "“查一下，这是一个真实的单词。”",
    "\"Money talk.\"": "\“金钱万能。\”",
    "\"Much wiser through the years.\"": "“随着岁月的流逝，我变得更聪明了。”",
    "\"Not decided yet on what to spend it on.\"": "“还没决定花在什么地方。”",
    "\"Oh yeah it is time.\"": "“哦，是时候了。”",
    "\"Peraphs too ready.\"": "“也许准备得太过充分。”",
    "\"Pluck.\"": "\"勇气。\”",
    "\"Really putting the 'Craft' in TurtleCraft.\"": "“真的是把‘工艺’放进了《TurtleCraft》。”",
    "\"Repaying just a bit of all your kindness.\"": "“对您好意的一点小小回礼。”",
    "\"Shattering your expectations.\"": "“不符预期。”",
    "\"Smokin' Sexy Style!\"": "“炫到冒烟!”\”",
    "\"Squish Splosh Splooch.\"": "“挤压飞洒喷溅。”",
    "\"Step 3: Profit.\"": "“第三步:利润。”",
    "\"That's a lotta damage.\"": "“好高的伤害。”",
    "\"That's a very disciplined tortuga.\"": "“这是一个非常有纪律的酷刑。”",
    "\"That's not the animal you want to click.\"": "“那不是你想要点击的动物。”",
    "\"The true method of knowledge is experiment.\"": "“获得知识的真正方法是实验。”",
    "\"Threading inbetween life and death.\"": "\"在鬼门关前徘徊\"",
    "\"To the shadow realm.\"": "“去往暗影王国。”",
    "\"Totally uncool, dude.\"": "“太不酷了，伙计。”",
    "\"Turtles can't possibly go to jail.\"": "“乌龟不太可能进监狱。”",
    "\"We still need you.\"": "“我们仍然需要你。”",
    "\"What do I like more than materialistic things? Knowledge.\"": "“比起物质层面，我更喜欢?”知识。\”",
    "\"Where will it take me?\"": "“它会带我通向哪里?”\”",
    "\"You make even the DEVIL CRY!\"": "“恶鬼也会为之哭泣!”\”",
    "[Stamps give specific damage bonuses to your weapon or, in rare cases, general ones such as Critical Chance]": "[图章将给你的武器盖印特定的伤害加成，或在极少数情况下，会印上暴击几率]",
    "★ Set bonus [5]: +250 Max HP": "★套装加成[5]:+250最大HP",
    "❖ Cloth Bracelet": "布手链",
    "❖ Cloth Pants": "布裤子",
    "❖ Cloth Shirt": "布衬衫",
    "❖ Cloth Slippers": "布鞋",
    "❖ Worn Bandana": "旧头巾",
    "Bury Me With...": "埋葬我和…",
    "Critical Thinking": "批判性思维",
    "Cultivated Mind": "培养的心灵",
    "Decked Out": "装饰完毕",
    "Gang Star": "帮派明星",
    "Here Comes The Money": "钱来了",
    "Heroes Never Die!": "英雄不死!",
    "Joker": "小丑",
    "Pawn Star": "典当之星",
    "Power Surge": "电涌",
    "Small Fortune": "小财富",
    "So I Just Need To Let It Run?": "所以我只需要让它运行?",
    "Advanced Adventurer": "熟练冒险家",
    "Applies or rerolls a random stamp to the currently equiped weapon, with a low chance of adding multiple stamp": "在当前装备的武器上应用或滚动一个随机印记，添加多个印记的几率很低",
    "Apprentice Workman": "学徒工人",
    "Assisted Atomisation": "辅助喷雾",
    "Beginner Adventurer": "初学者冒险家",
    "Big Brain": "大脑",
    "Big Dreams": "伟大的梦想",
    "Break a Drake": "打破僵局",
    "Christmas Is Cancelled": "圣诞节被取消",
    "Click on a Jester Turtle": "点击一只小丑龟",
    "Completed Book": "完成书",
    "Consumable - Recipe": "消耗品-配方",
    "Critical Thinking": "批判性思维",
    "Cultivated Mind": "培养思维",
    "Deal 100 Critical Hits": "造成100次暴击",
    "Decked Out": "打扮",
    "Destroy 100 Mysterious Presents": "摧毁100个神秘礼物",
    "Equip a full Set of armor": "装备全套护甲",
    "Fight Poison With Poison": "以毒攻毒",
    "Gang Star": "帮派明星",
    "Grateful Representation": "感恩的表示",
    "Here Comes The Money": "钱来了",
    "Heroes Never Die!": "英雄不死!",
    "Ill Take Your Entire Stock": "我要你的全部存货",
    "Joker": "小丑",
    "Learns how to create a Nephrite-Embedded Ring": "学习如何制作一个镶玉戒指",
    "Learns how to create the Net-o-Launcher 3000": "学习如何制作捕网器 3000",
    "Low chance to inflict a royal slash dealing 150-200 '+mightIcon+'Might Damage'": "低几率造成皇家砍伤，造成150-200“+强力剑+可能伤害”",
    "Lucky Streak": "幸运的条纹",
    "Master Adventurer": "大师冒险家",
    "Master Of My Craftship": "我的手艺大师",
    "Meat Beater": "肉搅拌器",
    "Missing Book": "丢失的书",
    "Monster Degree": "怪物学学位",
    "Monster Obsession": "怪物痴迷",
    "Nature Damage": "自然伤害",
    "New Heights": "一个新的高度",
    "Non Sellable": "不可出售",
    "Nothing Like The Present": "没什么比得上这礼物",
    "Once in a Blue Moon": "千载难逢",
    "One Punch Turtle": "一拳龟",
    "One way trip": "单程旅行",
    "Oniomaniac Therapy": "剁手族疗法",
    "Pat Pat Pat Pat Pat": "拍，拍，拍，拍，拍",
    "Perish 10 times": "死亡 10 次",
    "Play for 10 hours": "玩 10 个小时",
    "Potential Overflow": "潜在的溢出",
    "Quack.": "嘎。",
    "Sell 100K items.": "卖出10万件物品",
    "Sell 10K items.": "卖出1万件物品",
    "Small Fortune": "小财富",
    "So I Just Need To Let It Run?": "所以我只需要让它运行?",
    "Strong Guts": "强大的勇气",
    "Sweet Revenge": "甜蜜的复仇",
    "Tax Fraud": "税务欺诈",
    "Throws a wooden boomerang that deals 260-300": "投掷一个木制回飞镖，造成260-300的伤害",
    "Tortullionaire": "Tortullionaire",
    "Turtle Rabbithole": "乌龟兔子洞",
    "Ultrakill": "Ultrakill",
    "Unpresented Betrayal": "未提出的背叛",
    "Vive la Révolution": "革命万岁",
    "Whatever Did We Do?": "我们做了什么?",
    "You Shall be Known as...": "你将被称为……",
    "\"The stinger of a scorpid. Small traces of poison can be seen on the tip.\"": "“蝎子的毒刺。在尖端可以看到少量的毒药痕迹。”",
    "[Stamps]": "[印记]",
    "Learned!": "学会了!",
    "White Stinger": "白毒刺",
    "Miners Guild Request": "矿工公会委托",
    "Anyhow, these are some cookies I baked for you. Love you, Tortumom.": "总之，这些是我为你烤的饼干。爱你，折磨妈妈。",
    "Hi, my dear hatchling, hows over there, dear?": "嗨，我亲爱的小宝贝，那边怎么样，亲爱的?",
    "I'm hoping you can still recall your dear mother. Ive heard youve made the decision to pursue adventure. While I'm cheering you on from afar, just like any mother would, I'm still worried about my cub.": "我希望你还能想起你亲爱的母亲。我听说你决定去冒险了。虽然我在远处为你加油，就像所有母亲一样，但我仍然担心我的幼崽。",
    "PAT BOOST!": "拍拍提升!",
    "We will pray for your safety, every single one of us. I'm sure that you are assisting others and that you are not ignoring their requests. You better not.": "我们会为你的安全祈祷，我们每一个人。我确信你是在帮助别人，而不是忽视他们的要求。你最好不要。",
    "\"(Unbeatable)\"": "\”(无敌)\”",
    "\"And they don't stop coming...\"": "“他们不停地来……”",
    "\"And this will be my last one.\"": "“这将是我最后一次。”",
    "\"And without angering the shopkeeper.\"": "“而且不能惹店主生气。”",
    "\"At least it farms itself.\"": "“至少它自己种田。”",
    "\"Bad day to be made out of fire.\"": "“真是倒霉的一天。”",
    "\"But the new update...\"": "“但是新的更新……”",
    "\"Caught red handed.\"": "“被抓个正着。”",
    "\"Go show it to an owl or something.\"": "“去给猫头鹰什么的看看吧。”",
    "\"Gunther would like to have a word with you.\"": "“冈瑟想跟你说句话。”",
    "\"Have you been studying a lot?\"": "“你最近学习很多吗?”\”",
    "\"I don't care who it was, they are now mine.\"": "“我不在乎是谁，他们现在是我的了。”",
    "\"I feel so... Informed.\"": "“我觉得……通知。\”",
    "\"I just don't want to.\"": "“我只是不想。”",
    "\"I just wanted to salt the salad...\"": "“我只是想在沙拉里加点盐……”",
    "\"I'm you but stronger.\"": "“我是你，但更强大。”",
    "\"Ill take you to burn.\"": "“我要带你去烧。”",
    "\"It all comes tumbling down, tumbling down, tumbling down...\"": "“一切都滚下来，滚下来，滚下来……”",
    "\"It escaped.\"": "\“它逃脱了。\”",
    "\"It was worth a try.\"": "“值得一试。”",
    "\"It wasnt such a special catch after all...\"": "“这并不是什么特别的收获……”",
    "\"It's a secret to everybody.\"": "“这对每个人来说都是秘密。”",
    "\"It's like he never left...\"": "“好像他从未离开过……”",
    "\"It's shrimple.\"": "\“这是虾皮。\”",
    "\"It's work o clock.\"": "“现在是上班时间。”",
    "\"Let him cook.\"": "“让他做饭吧。”",
    "\"Nice.\"": "\“很好。\”",
    "\"Should had brought a cat.\"": "“我应该带只猫来的。”",
    "\"Thank you for your service.\"": "“谢谢你的服务。”",
    "\"Thank you, kind stranger.\"": "“谢谢你，好心的陌生人。”",
    "\"The tortuga always had my heart anyways\"": "“不管怎样，我的心一直都在那个恶魔手里。”",
    "\"The turtle remains undefeated.\"": "“乌龟永远不会被打败。”",
    "\"Their flavor is quite familiar. Nothing happens if you press them, though.\"": "“它们的味道很熟悉。不过，如果你按它们，什么也不会发生。”",
    "\"This coin will take me out poverty.\"": "“这枚硬币将使我摆脱贫困。”",
    "\"This is not the adventure I signed for.\"": "“这不是我想要的冒险。”",
    "\"This one is going to the wall.\"": "“这个人要完蛋了。”",
    "\"Turtles and spiders were never meant to be friends.\"": "“乌龟和蜘蛛从来就不是朋友。”",
    "\"Way faster than any children.\"": "“比任何孩子都快。”",
    "\"Who are you going to call?\"": "“你要给谁打电话?”\”",
    "\"You criminal scum.\"": "“你这个犯罪渣滓。”",
    "\"You got all us laughing.\"": "“你把我们都逗笑了。”",
    "\"You must defeat tortuga to stand a chance.\"": "“你必须打败托图加才有机会。”",
    "\"Your pityful average protagonist can only get one of these.\"": "“你可怜的普通主角只能得到其中的一个。”",
    "A fine collection": "精美的收藏品",
    "Arachnophobia": "蜘蛛恐惧症",
    "Awww Man": "幸福的男人",
    "Back in Black": "黑衣重现",
    "Big Game": "大游戏",
    "Blast Fishing": "爆炸钓鱼",
    "Chocolate Chip Cookies": "巧克力饼干",
    "Containment Breach": "遏制违反",
    "Encased Forever": "包裹永远",
    "Et tu, Bunnytus?": "你呢，兔兔?",
    "Extinguished": "熄灭",
    "Fast Learner": "快速学习者",
    "Feed it to the turtle": "把它喂给乌龟",
    "Final Eden": "最后的伊甸园",
    "Gambling Addiction": "赌瘾",
    "God of Hell Fire": "地狱火神",
    "Honest Mistake": "诚实的错误",
    "I Can Stop Whenever I want": "我可以随时停止",
    "It All Returns to Nothing": "一切归于虚无",
    "Jack Of All Trades": "万事通",
    "Knowledge Garden": "知识的花园",
    "Luck Issue": "运气问题",
    "Monster Foster": "怪物培养",
    "Mysterious Benefactor": "神秘的恩人",
    "Nice.": "好了。",
    "Officework": "办公室工作",
    "Or Maybe Not?": "或许不是?",
    "Path of the Hero": "英雄之路",
    "Phantom Thief": "幽灵的小偷",
    "Red Herring": "红鲱鱼",
    "Salt Splash": "盐飞溅",
    "Stop Right There": "就此打住",
    "Super Turtle Grinder": "超级龟磨机",
    "Take a Break": "休息一下",
    "The Architect": "架构师",
    "The Entire Circus": "整个马戏团",
    "This One Officer": "这一位警官",
    "Turtle Champion": "乌龟冠军",
    "Turtle Labor": "乌龟劳动",
    "Turtle Spelunky": "乌龟洞穴探险",
    "Tuxedo Friends": "燕尾服的朋友",
    "Who Left All These Here?": "谁把这些东西留在这儿的?",
    "World Record Any%": "世界纪录",
    "A rich mineral deposit containing soft metals.": "含软金属的丰富矿床。",
    "Copper Vein": "铜脉",
    "Press to mine the vein of this area.": "按下可开采该区域的矿脉。",
    "Resource": "资源",
    "\"A blossoming blade emerging from the heart of the forest. Like plantlife, it can harness sunlight to gain strength.\"": "“一片花开的叶子从森林的中心冒出来。像植物一样，它可以利用阳光来获得力量。”",
    "\"A fierce ring made out of thorns and blossoms. To inflict pain one must be ready to receive pain.\"": "“一个用荆棘和花朵做成的凶狠的戒指。要施加痛苦，就必须准备好接受痛苦。”",
    "\"A striking green mineral, prized for its vivid color and used in jewelry for centuries.\"": "“一种引人注目的绿色矿物，因其鲜艳的颜色而备受珍视，几个世纪以来一直用于制作珠宝。”",
    "\"meow meow meow.\"": "“喵喵喵。”",
    "\"Often used in jewelry and believed to bring strength and healing properties.\"": "常用于珠宝中，被认为能带来力量和治疗效果。",
    "Low chance to trigger photosynthesis, increasing your": "触发光合作用的几率很低，增加你的",
    "Low chance to trigger photosynthesis, increasing your '+natureIcon+'Nature Damage by 15% and heal based on your current nature bonus'": "触发光合作用的几率低，增加你的“+natureIcon+”自然伤害15%，并根据你当前的自然加成治疗",
    "Nature Damage by 15% and heal based on your current nature bonus": "自然伤害提高15%，并根据你当前的自然伤害加成进行治疗",
    "Reflects damage received back to the enemy as": "将受到的伤害反射回敌人",
    "The enemy shows its fangs!": "敌人露出了毒牙!",
    "\"Symbolizes wisdom and loyalty.\"": "“象征智慧和忠诚。”",
    "Whiskers": "胡须",
    "Sapphire": "蓝宝石",
    "\"Seems like it really doesn't belong in this world.\"": "\“看起来它真的不属于这个世界。\”",
    "\"Spiders not included, and it's for the best.\"": "\“蜘蛛不包括在内，这是最好的。”",
    "❖ Chrysalis Recurver": "❖ Chrysalis Recurver",
    "❖ Creeping Wolf Web": "❖ 匍匐狼网",
    "❖ Hoopperona's Phylactery": "❖ Hoopperona 的护符",
    "❖ Web-Threaded Promise": "❖ 网络线程预示",
    "Combine 4 into a Reality Cube": "将4组合成一个现实立方体",
    "Wolf Spider Cache": "狼蛛缓存",
    "Area": "区域",
    "???? ATK": "???? 攻击",
    "???? EXP": "???? 经验值",
    "???? HP": "???? 生命值",
    "“ My cat Whiskers is missing. He likes dark closed spaces. I have nothing to offer but Whiskers grattitude. ”": "“我的猫胡须不见了。他喜欢黑暗封闭的空间。我没有什么可以给你的，只有胡须的态度。”",
    "“ My chickens escaped from my coop and learnt full body combat. Help me bring them back. ”": "“我的鸡从鸡笼里逃出来，学会了全身格斗。帮我把他们带回来。”",
    "“ Teach him a lesson on my behalf. I would do it if it wasnt a 3 meter tiger proficient in breaking bones.": "“代表我给他上一课。如果这不是一只精通折断骨头的3米高的老虎，我会这么做的。",
    "“ The animals punched the heck out of our workshops. We will let anyone who help us repair them into the Crafters Guild. ”": "“动物们把我们的车间打得一团糟。我们会让任何帮助我们修理它们的人加入工匠公会。”",
    "“ These animals got hands. I need something to make them learn a lesson or two about martial arts. ”": "“这些动物有手。我需要一些东西让他们学一两节武术。”",
    "“ To beat a squirrel I need to become a squirrel. Help me achieve my dream. ”": "“要打败松鼠，我需要变成一只松鼠。帮助我实现我的梦想。”",
    "\"A supple and furry hide harvested from rabbits. Regretting now is useless, the deed has been done.\"": "兔皮:从兔子身上获得的柔软而毛茸茸的皮现在后悔是没有用的，事情已经做了。”",
    "\"Destruction awaits for the enemies of Whiskers.\"": "“毁灭正等着胡须的敌人。”",
    "\"Protection awaits for the friends of Whiskers.\"": "“保护等待着胡须的朋友们。”",
    "\"Ribbit.\"": "\" Ribbit。\”",
    "\"The stars are gleaming through the crustacean's surface.\"": "“星星在甲壳类动物的表面闪烁。”",
    "\"This one always puts a gleaming smile on your face.\"": "“这个总能让你脸上露出灿烂的笑容。”",
    "[+ 10% Drop Chance]": "[+ 10%掉落几率]",
    "[Tip: Area bosses can generally be tough to beat without first dabbling on the next area or coming a bit later] ”": "[提示:如果不先进入下一个区域或稍晚进入下一个区域，区域boss通常很难被打败]”",
    "❖ Capture 10 Roostrikas": "捕获10只知更鸟",
    "❖ Defeat 80 Karateil": "打败80个空手道",
    "❖ Defeat King-Kat": "打败King-Kat",
    "❖ Find Whiskers": "寻找胡须",
    "❖ Hand over 10 Light Dynamites": "交 10 Light Dynamites",
    "❖ Hand over 100 copper ore": "交 100 铜矿",
    "❖Hand over 100 rabbit hi": "交 100 兔子皮",
    "A common red squirrel that has found its ways into martial arts. Not so common anymore.": "一只普通的红松鼠在武术中找到了自己的方法。现在不常见了。",
    "A hen proeficient in full body combat. This one doesn't even want to cross the road.": "母鸡擅长全身格斗的母鸡这只甚至不想过马路。",
    "A very corny request": "一个非常老土的请求",
    "Access to the Guildwork Tab": "进入公会工作选项卡",
    "Acorn": "橡子",
    "Although it lacks poison or claws, does it really look like it couldn't hurt you?": "虽然它没有毒液和爪子，但它真的看起来不会伤害你吗?",
    "Angry Cat Token": "愤怒猫信物",
    "Can be used to reset Talent Points": "可以用来重置天赋点吗",
    "Crafters Guild Request": "工匠公会请求",
    "Deal 1K Damage in one hit": "一次攻击造成1K伤害",
    "Defeat the boss of Cradle Hills": "击败摇篮山的boss",
    "Drop Voucher": "下降凭证",
    "Friendly Cat Token": "友好猫令牌",
    "Fully upgrade this item to complete the entry and unlock its potential": "完全升级此物品以完成条目并释放其潜力",
    "Help! Missing Feline": "的帮助!丢失的猫",
    "Husbandry Issues": "农业问题",
    "Jabbit": "Jabbit",
    "Karateil": "Karateil",
    "Rabbit Hide": "兔子皮",
    "Rana Hat": "拉纳帽",
    "Reflects damage received back to the enemy as '+natureIcon+'Nature Damage up to a maximum of '+ returnItemUpgradeScaling(312, \"I131\")+' damage'": "将收到的伤害反射回敌人为'+natureIcon+'自然伤害最高'+ returnItemUpgradeScaling(312， \"I131\")+'伤害'",
    "Requires [Black Belt] x1": "需要[黑带]x1",
    "Roostrika": "Roostrika",
    "Sovereign Affairs": "主权事务",
    "The Way Of Karate": "空手道之道",
    "Unlock Herb Node": "解锁草药节点",
    "Whiskers Gratitude": "胡须的感激之情",
    "\"A ceremonial blade used in festivities and joyous days.\"": "\"在节日和欢乐的日子里使用的仪式用刀。\"",
    "\"A picture book full of details and photos of cute foes. Calling them monsters would be a farce.\"": "“一本充满细节和可爱敌人照片的图画书。称他们为怪物是一场闹剧。”",
    "\"A specialized flask crafted from materials designed to interact with alchemical substances.\"": "\"一种特殊的烧瓶，由能与炼金术物质相互作用的材料制成。\"",
    "\"A standard cage with a standard chicken-shaped hole inside.\"": "“一个标准的笼子，里面有一个标准的鸡形洞。”",
    "\"Full of nutrients and good stuff for your body, unfortunately.\"": "“很不幸，它富含营养，对你的身体有好处。”",
    "\"Hit Hard! Hit Fast! Hit Often!\"": "\"重创!打了快!打经常!\”",
    "\"Lost for not much longer.\"": "“没过多久就迷路了。”",
    "\"Maybe it doesn't give the warmest pats, but it gives the most secure and firm ones.\"": "“也许它不会给你最温暖的爱抚，但它会给你最安全、最坚定的爱抚。”",
    "\"No creature should suffer this fate.\"": "“任何生物都不应该遭受这种命运。”",
    "Add this book to the archives": "把这本书加入档案库",
    "Broccoli": "西兰花",
    "Cage a chicken": "把鸡关进笼子",
    "Chicken Cage": "鸡笼",
    "Copperwork Axe": "铜制斧头",
    "Dead Man Emblem": "亡灵徽章",
    "Festive Wakizashi": "节日Wakizashi",
    "Frog Pho": "青蛙越南河粉",
    "Glass Flask": "玻璃烧瓶",
    "Heals 12000-13000 HP if your health goes below 50%": "如果你的生命值低于50%，治疗12000-13000 HP",
    "High-Grade Anvil": "高档砧",
    "Ironwork Gloves": "铁制品手套",
    "Learns how to cook Frog Pho": "学习如何烹饪青蛙粉",
    "Learns how to craft the Copperwork Axe": "学习如何制作铜制斧头",
    "Lost Book": "丢失的书",
    "Monster Bestiary": "怪物动物寓言集",
    "Permanently enables the auto-summoning of bosses once the current one gets defeated. Right click on the boss button to toggle": "一旦当前的boss被打败，永久启用自动召唤boss。右键点击boss按钮切换",
    "Permanently increases Turtle Coin reward from clicking by +100": "永久增加海龟币点击奖励+100",
    "Permanently reduces the crafting time of all recipes by 5 seconds": "永久减少所有配方的制作时间5秒",
    "Permanently unlocks the Bestiary at the top of the screen. Defeat an enemy multiple times to fill out their entry": "永久解锁屏幕上方的兽书。多次击败一个敌人来填入他们的入口",
    "\"A damp cave imbued with magical ore. the combination of the minerals and the natural electromagnetism has breed both terrifying and cute creatures.\"": "“一个充满神奇矿石的潮湿洞穴。矿物和自然电磁的结合孕育了既可怕又可爱的生物。”",
    "\"A land devoid of life. Death always finds its way, and the ghostly remains of the undead torment the living in mortuary anger. I also heard there is a cute cat in here.\"": "“一片没有生命的土地。死亡总有它自己的路，亡灵的幽灵遗骸在太平间的愤怒中折磨着活着的人。我还听说这里有一只可爱的猫。”",
    "\"If a turtle wore boxing gloves, would they wear them like this or...?\"": "“如果乌龟戴拳击手套，它们会这样戴还是……?”\”",
    "\"Legends say that a martial dojo was abandoned in the heart of the forest. Overtime, animals began honing their moves in there, and today hardly anyone can live to tell the tale.\"": "“传说有一个武馆被遗弃在森林的中心。随着时间的推移，动物们开始在那里磨炼自己的动作，今天几乎没有人能活着讲述这个故事。”",
    "\"The starting point of many turtle adventurers due to bugs and insects being the only residents around here, which makes for an easy prey. Or at least it should be.\"": "“这是许多海龟冒险家的起点，因为这里只有虫子和昆虫，很容易被捕食。或者至少应该是这样。”",
    "\"Welcoming all brave turtles, this thunderdome is a place of glory and riches. Fight against powerful foes and claim prize for yourself!.\"": "“欢迎所有勇敢的海龟，这个雷穹是一个荣耀和财富的地方。与强大的敌人战斗，为自己争取奖品!”",
    "❖Hand over 100 rabbit hide": "赠送超过100张兔子皮",
    "Boxing Gloves": "拳击手套",
    "Low chance to knock out the enemy, interrupting their attack": "低几率击倒敌人，打断他们的攻击",
    "You dont meet the level requirement for this area": "你不符合这个地区的等级要求",
    "Right Click to open it!": "右键点击打开它!",
    "Quick, Before you \"accidentally\" destroy it!": "Quick, Before you \"accidentally\" destroy it!",
    "\"Better not to mess too much with this one.\"": "“最好不要把这个弄得太乱。”",
    "\"Mythical concoction that it's said to enhance the muscular mass of whoever that consumes it.\"": "“传说中的混合物，据说吃了它的人可以增强肌肉质量。”",
    "Can be used to summon King-Kat": "可以用来召唤 King-Kat",
    "Proteiny Relic": "蛋白质遗物",
    "King of the jungle and king of all fighting styles. Try hitting its weakness.": "丛林之王，所有格斗风格之王。试着打击它的弱点。",
    "Elemental Damage": "元素伤害",
    "“ I'm going to make the finest of armors and I need the finest of materials. ”": "“我要做最好的盔甲，我需要最好的材料。”",
    "“ Lately I'm getting pretty restless over what I lost playing near the pond, can you get it for me? ”": "“最近我在池塘边玩耍时丢了东西，心里很不安，你能帮我找回来吗?”",
    "“ That... Thing... Hand it over... I can make something useful... For you... ”": "“那……事情。把它交出来……我可以做一些有用的东西……给你……”",
    "“ The adventurer's guild has reported sightings of a fiery monster several times more powerful than the rest. ”": "“冒险家公会报告说，他们看到了一只烈性怪物，其威力是其他怪物的数倍。”",
    "“ The lord of hell fire stole my grill. I think his reign over fiery goods has gone too far. ”": "\"地狱之王偷走了我的烤架。我觉得他对烈性物品的统治太过分了。”",
    "“ This depressing scenary is tooootaly making me unconfortable. Bring me something to drink. ”": "“这种令人沮丧的场景让我感到非常不舒服。给我拿点喝的来。”",
    "“ Well this is fantastic. Now the ghosts are throwing their own floating party. ”": "“这太棒了。现在鬼魂们正在举办他们自己的水上派对。”",
    "“ You feel the powerful aura, yes? I need a powerful exorciser to aid me on this Job. ”": "“你感觉到了强大的气场，是吗?”我需要一个强大的驱魔人来帮我做这件事。”",
    "\"A captivating jewelry piece with a malachite gemstone intricately set within the ring. The adept gemstone represents might itself.\"": "“这是一件迷人的珠宝，戒指内镶嵌着一颗孔雀石宝石。熟练的宝石代表了力量本身。”",
    "\"A captivating jewelry piece with a nephrite gemstone intricately set within the ring. The lush gemstone represents nature itself.\"": "“这是一件迷人的珠宝，戒指内镶嵌着一颗软玉宝石。郁郁葱葱的宝石代表着大自然本身。”",
    "\"A container with materials necessary to construct various structures.\"": "“装有建造各种结构所需材料的容器。”",
    "\"A device that can harness electricity and discharge it right at the enemy spot.\"": "“一种可以利用电流并在敌人的位置直接放电的装置。”",
    "\"A ductile, malleable, and highly thermal metal. Despite being very versatile, it makes for inadequate weaponry.\"": "“一种延展性、延展性和高热性的金属。尽管用途非常广泛，但它不足以成为武器。”",
    "\"A fiery red scale, hewn from a crystal dragon, pulsating with potent mystical energy.\"": "“火红的鳞片，从水晶龙身上切割而成，跳动着强大的神秘能量。”",
    "\"A hard rock from a rock hard foe.\"": "“坚硬的石头来自坚硬的敌人。”",
    "\"A lackluster catch.\"": "“毫无亮点。”",
    "\"A leaf shining as dazzling as sunlight.\"": "“一片像阳光一样耀眼的叶子。”",
    "\"A mesmerizing essence pulsates within.\"": "“一种迷人的本质在你内心搏动。”",
    "\"A mysterious earthy chunk of marine-like shade glistening ore.\"": "“一块神秘的泥土，像海洋一样的阴影闪闪发光的矿石。”",
    "\"A practical cloud of chalk dust for athletes. Keeps your grip solid and hands dry.\"": "“运动员用的实用粉笔尘。”让你握得结实，手也干爽。”",
    "\"A shimmering, iridescent powder valued for its reactivity in alchemy.\"": "一种闪光的、闪光的粉末，因其在炼金术中的反应性而受到重视。",
    "\"A small, nut-like seed from oak trees. Additionally, in the Squirrel Kingdom, it's a standard form of currency.\"": "“橡树上的一种小的坚果状种子。此外，在松鼠王国，它是一种标准的货币形式。”",
    "\"A spice known for its sweet licorice-like flavor.\"": "一种以甘草般的甜味而闻名的香料。",
    "\"A spooky scary blade with an otherworldly edge. It sends shivers down your spine.\"": "“一把有着超凡脱俗边缘的阴森恐怖的剑。它会让你脊背发冷。”",
    "\"A sprawling cobweb, intricately woven by an enormous forest-dwelling spider.\"": "“一张庞大的蜘蛛网，由栖息在森林里的巨大蜘蛛精心编织而成。”",
    "\"A wickedly enchanted gourd with savory dark magic sprinkled on top.\"": "“一个施了邪恶魔法的葫芦，上面撒着美味的黑魔法。”",
    "\"Also known as fireball.\"": "“也被称为火球。”",
    "\"An eerie, creaking log. Its ominous aura makes you feel uneasy.\"": "“一根怪异的、吱吱作响的木头。它不祥的气氛让你感到不安。”",
    "\"An iron badge commemorating a seasoned adventurer.\"": "“一枚纪念经验丰富的冒险家的铁徽章。”",
    "\"As reinforced as wood can be.\"": "“木头能有多坚固就有多坚固。”",
    "\"Doesn't seem like it will be easy to bring this to a plate.\"": "“把这事摆到盘子里似乎不太容易。”",
    "\"Doink.\"": "\" Doink。\”",
    "\"Hardened, sharp cobweb in the shape of a ring.\"": "“坚硬、锋利的蛛网，形状像一个环。”",
    "\"High temperature rocks are poured into the stew for heating. You are not supposed to eat them, but I'm not a cop.\"": "把高温的石头倒进炖菜里加热。你不应该吃它们，但我不是警察。”",
    "\"Highly volatile dust primarily used for explosives.\"": "“主要用于炸药的高度挥发性粉尘。”",
    "\"How do we cook this one.\"": "“我们怎么煮这个?”",
    "\"I bet they are adding a battle royale with this one.\"": "“我打赌他们会在这款游戏中加入大逃杀。”",
    "\"Includes camouflage.\"": "\”包括伪装。\”",
    "\"Isnt that just a ring, though.\"": "“那不只是一个戒指吗?”",
    "\"It appears to be single-barreled.\"": "“看来是单管枪。”",
    "\"It feels like a waste to smash this onto a rock.\"": "“把它砸在石头上感觉太浪费了。”",
    "\"It's just trash.\"": "“都是些垃圾。”",
    "\"It's not going anywhere though.\"": "“不过它哪儿也去不了。”",
    "\"Luck Be A Turtle.\"": "“幸运是一只乌龟。”",
    "\"May have lingering effects on the soul, but it's definitely worth it.\"": "“可能会对灵魂产生挥之不去的影响，但绝对值得。”",
    "\"Not that they are much of use for you.\"": "“倒不是说它们对你有多大用处。”",
    "\"Nothing appears to be refracted on the edge but the blue hue of the moon.\"": "“除了月亮的蓝色外，似乎没有任何东西在边缘被折射。”",
    "\"Oh. So that's what it was talking about.\"": "\"哦。这就是它所说的。”",
    "\"One kilogram of this weight is surprisingly the same as a lot of stuff.\"": "“这种重量的一公斤和很多东西的重量惊人地相同。”",
    "\"Pure dread, harvested from the accursed grounds where nightmares manifest into tangible horrors.\"": "“纯粹的恐惧，来自被诅咒的土地，在那里噩梦变成了实实在在的恐怖。”",
    "\"Remember the rule. The less practical the shape, the stronger it is.\"": "“记住规则。形状越不实用，就越坚固。”",
    "\"Screws made out of arcanite that boast better resistance and conductivity than non-fictional metals.\"": "“由奥秘石制成的螺丝，比非虚构的金属具有更好的电阻和导电性。”",
    "\"Sinister prison pulsating with the anguished cries of captive souls.\"": "“邪恶的监狱里回荡着被囚禁的灵魂痛苦的呼喊。”",
    "\"Slimy yet satisfying.\"": "“黏糊糊的，但令人满意。”",
    "\"Something might happen if you eat this.\"": "“如果你吃了这个，可能会发生什么事。”",
    "\"That will be 12.99$.\"": "“一共12.99美元。”",
    "\"Today seems like a good day to buy lottery.\"": "“今天看来是个买彩票的好日子。”",
    "\"Tunk.\"": "\“重击。\”",
    "\"Versatile material used in various crafting, valued for its strength and adaptability.\"": "“用于各种工艺的多功能材料，因其强度和适应性而受到重视。”",
    "\"We don't talk about the other 2999.\"": "“我们不谈论其他的2999。”",
    "\"You feel uncomfortable carrying more than 64 of these at a time.\"": "“一次携带超过64个这样的东西会让你感到不舒服。”",
    "\"Your shell quakes in fear at the echo of it.\"": "“你的壳在它的回声中恐惧地颤抖。”",
    "-Embedded Ring": "-镶嵌戒指",
    "(Doesn't work past reaching Level 30)": "(超过30级就不工作了)",
    "(Only one bait can be active at a time)": "(一次只能激活一个鱼饵)",
    "(Only one food buff can be active at a time)": "(一次只能激活一个食物buff)",
    "(Only one potion buff can be active at a time)": "(一次只能激活一个药水buff)",
    "(Right Click to activate)": "(右击可启动)",
    "[Current Bonus: 0%]": "[当前加成:0%]",
    "<Apprentice>": "<学徒>",
    "⚠ Not currently used in this version of the game, BUT. Do hold into it, because it will become something very cool on the next version.": "目前在这个版本的游戏中没有使用，但是。一定要坚持下去，因为它会在下一个版本中变得非常酷。",
    "❖ 1 [Artisan Supply Box]": "[工匠用品箱]",
    "❖ 1 [Mossy Supply Box]": "[苔藓补给箱]",
    "❖ 1 [Rocky Supply Box]": "[岩石补给箱]",
    "❖ 1 [Sporty Supply Box]": "[运动用品盒]",
    "❖ 500K [Turtle Coins]": "500K [乌龟金币]",
    "❖ Clear the Pirate Galleon": "清除海盗帆船",
    "❖ Defeat Infernalus": "打败ininalus",
    "❖ Exorcise 3 Morgatos with salt": "用盐驱除3个摩加托",
    "❖ Hand over 15 Pumkin Spice Latte": "交15个南瓜拿铁",
    "❖ Hand over 200 Nightmare Fuel": "交200个噩梦燃料",
    "❖ Hand over 600 Agate Crystal Scales": "手超过600玛瑙水晶鳞片",
    "❖ Hand over the lost item on the pond": "把池塘里丢失的东西交出来",
    "❖ Heart of Tortugas": "托尔图加斯之心",
    "❖ Recipe: Malachite-Embedded Ring": "配方:孔雀石镶嵌戒指",
    "❖ Recipe: Soul Canister": "诀窍:灵魂罐",
    "❖ Reinforced Stamper": "强化冲压件",
    "❖ Sacrificial Dagger": "祭祀用匕首",
    "❖ Steal back the grill from Infernalus": "从炼狱里偷回烤架",
    "A shadow-laden pond cloaked in an eerie mist. Grab a fishing rod and don't get your hopes too high.": "阴影密布的池塘笼罩在诡异的迷雾中。拿起鱼竿，不要抱太大希望。",
    "Agate Crystal Scale": "玛瑙水晶鳞片",
    "Algae": "藻类",
    "Anima Anvil": "生命砧",
    "Applies a damaging curse that deals 90K": "施放一个伤害性诅咒，造成90K伤害",
    "Applies or rerolls a random stamp to the currently equiped weapon, always adding multiple stamps": "对当前装备的武器应用或滚动一个随机印记，总是添加多个印记",
    "Applies or rerolls a random stamp to the currently equiped weapon, with a high chance of adding multiple stamps": "在当前装备的武器上应用或滚动一个随机印记，有很高的几率添加多个印记",
    "Arcanite Bar": "奥金锭",
    "Arcanite Blasting Charge": "奥术爆破药",
    "Arcanite Bolts": "奥金螺栓",
    "Arcanite Ore": "奥金矿",
    "Arcanite Vein": "奥金矿脉",
    "Artisan Supply Box": "工匠用品箱",
    "Auto-summon is turned OFF": "自动召唤被关闭",
    "Begone Dark Presences": "离开黑暗的存在",
    "Blacksmith Request": "铁匠请求",
    "Buff": "增益",
    "Bunny Inferno": "兔子地狱",
    "Burns the soul of the enemy inflicting": "燃烧敌人的灵魂施加",
    "Caladora": "Caladora",
    "Can be used once to reveal the details of a missing book": "能用一次来揭示丢失的书的细节吗",
    "Can be used to open Novice Locks": "可以用来打开新手锁吗",
    "Can be used to summon Infernalus": "可以用来召唤阴尸吗",
    "Cap. Plundergeist": "掠夺者队长",
    "Chalk Dust": "粉笔的灰尘",
    "Champion Finger Belt": "冠军指带",
    "CLICK SUPERBOOST!": "点击超级加成!",
    "Combine the clover, the spade, the heart and the diamond into a deck": "将三叶草、黑桃、红心和方块组合成一副牌",
    "Consumable - Food": "消耗品 - 食物",
    "Creates a Arcanite Bar": "创造一个奥秘条",
    "Creates a Arcanite Blasting Charge": "制造一个奥术爆破药",
    "Creates a Arcanite Bolts": "制造一个秘法螺栓",
    "Creates a Arêtes de Poisson Frites": "创建Arêtes de Poisson Frites",
    "Creates a Artisan Supply Box": "创建一个工匠供应箱",
    "Creates a bunch of Arcanite Bolts": "制造一堆奥术螺栓",
    "Creates a Copper Bar": "制作一个铜棒",
    "Creates a Copper Key": "创建一个铜密钥",
    "Creates a Copper Plate": "制作一个铜板",
    "Creates a Copperwork Axe": "制造一把铜制斧头",
    "Creates a Dayleaf Spice": "创造一种日叶香料",
    "Creates a Devilfish Sashimi": "做一个章鱼生鱼片",
    "Creates a Frog Pho": "制作青蛙粉",
    "Creates a Ghastly Supply Box": "创建一个可怕的补给箱",
    "Creates a Granite Pachamanca": "创建一个花岗岩Pachamanca",
    "Creates a Healing Potion": "创造一个治疗药水",
    "Creates a Lesser Alchemical Dust": "制造低级炼金术之尘",
    "Creates a Lesser Elemental Flask": "制造一个低元素烧瓶",
    "Creates a Lesser Healing Flask": "制造一个低级治疗瓶",
    "Creates a Lesser Might Flask": "制造一个小力量瓶",
    "Creates a Lesser Nature Flask": "创造一个低级瓶",
    "Creates a Lesser Poison Flask": "制造一个小毒瓶",
    "Creates a Light Dynamite": "制造一个轻型炸药",
    "Creates a Malachite-Embedded Ring": "创建孔雀石镶嵌戒指",
    "Creates a Masala Chai": "做一个玛莎拉茶",
    "Creates a Monster Sausage": "创造一个怪物香肠",
    "Creates a Mossy Supply Box": "创建一个苔藓补给箱",
    "Creates a Nephrite-Embedded Ring": "创造一个镶有软玉的戒指",
    "Creates a Net-O-Launcher 3000": "创建一个 网络启动器 3000",
    "Creates a piece of gear of the Plated Explorer Set": "生成一件“镀甲探索者”套装的装备",
    "Creates a Plated Explorer Boonie": "创建一个镀金的探险家Boonie",
    "Creates a Plated Explorer Boots": "创建一个被镀的探索者靴子",
    "Creates a Plated Explorer Cuirass": "创建一个镀银探险家铁甲",
    "Creates a Plated Explorer Gloves": "创建一个镀面资源管理器手套",
    "Creates a Plated Explorer Pants": "创建一条被镀的探险家裤子",
    "Creates a Pumpkin Spice Latte": "制作南瓜拿铁",
    "Creates a Reinforced Stamper": "创建一个加强版",
    "Creates a Rocky Supply Box": "创建一个岩石补给箱",
    "Creates a Shatterstone Potion": "制造一个碎裂石药水",
    "Creates a Shiny Fishing Lure": "创造一个闪亮的鱼饵",
    "Creates a Soul Canister": "制造一个灵魂罐",
    "Creates a Sporty Supply Box": "创建一个运动用品箱",
    "Creates a Thunderous Gyroresonator": "创造一个雷鸣般的回旋共振器",
    "Creeping Wolf Web": "爬行狼网",
    "Cubomite": "立方石",
    "Dayleaf": "黄叶",
    "Debuff": "减益",
    "Devilfish Sashimi": "章鱼生鱼片",
    "Devilish Pumpkin": "邪恶的南瓜",
    "Diamond of Tortugas": "托图加斯钻石",
    "Dungeon": "地牢",
    "Eerie Pond": "怪异的池塘",
    "Exorcism Aboard": "上的驱魔",
    "Feather Pinion": "羽毛小齿轮",
    "Firekeg Cannon": "火桶炮",
    "Firetank Pyrocombulator": "火罐燃烧器",
    "Fish Bait": "鱼饵",
    "Ghastly Supply Box": "可怕的供应箱",
    "Ghost Jellyfish": "鬼水母",
    "Golden Clover": "金色的三叶草",
    "Golden Magnifying Glass": "黄金放大镜",
    "Granite Elemental": "花岗岩元素",
    "Granite Pachamanca": "花岗岩Pachamanca",
    "Granite Splinter": "花岗岩分裂",
    "Gunpowder": "火药",
    "Healing Potion": "治疗药水",
    "Heart of Tortugas": "托图加斯之心",
    "Hell Bindings": "地狱绑定",
    "Hex Tag": "十六进制标签",
    "Hollog": "全记录仪",
    "Increases": "增加",
    "Increases Fishing Level by 1 for 30 Minutes": "提高钓鱼等级1点，持续30分钟",
    "Increases Max HP by 5% per level": "每升一级最大生命值提高5%",
    "Increases Offline Power by 10% per level": "每升一级增加10%的离线能量",
    "Increases Regeneration 5% per level": "每升一级增加5%的回复速度",
    "Increases Strength by 6% per level": "每升一级增加6%的力量",
    "Infernalus": "炼狱",
    "Iron Adventurer Badge": "钢铁冒险家徽章",
    "Launch an explosive cannonball": "发射爆炸性炮弹",
    "Launch an explosive cannonball'": "发射一颗爆炸性炮弹。”",
    "Launches a net that immobilises the enemy for 10 seconds": "发射一张网，使敌人动弹不得10秒",
    "Left Click to": "左键点击以",
    "Legendary": "传说",
    "Lesser Deific Flask": "小仙瓶",
    "Lesser Elemental Flask": "小元素瓶",
    "Lesser Healing Flask": "小治疗瓶",
    "Lesser Might Flask": "小力量瓶",
    "Lesser Nature Flask": "小自然瓶",
    "Lesser Occult Flask": "小奥术瓶",
    "Lesser Poison Flask": "小毒瓶",
    "Light Dynamite": "光炸药",
    "Losing Life": "失去生命",
    "Low chance to gain Blessing of the Moon, converting every normal attack into moon slashes": "获得月之祝福的几率低，将每次普通攻击转化为月之砍伤",
    "Low chance to gain Blessing of the Moon, converting every normal attack into moon slashes'": "获得月之祝福的几率很低，将每次普通攻击转化为月之砍伤",
    "Malvarrel": "Malvarrel",
    "Miscellaneous - Treasure": "杂项-宝藏",
    "Monster Hunt Request": "捉妖请求",
    "Monster Sausage": "怪物香肠",
    "Moonlit Greatsword": "月光下的巨剑",
    "Morgato": "Morgato",
    "Mossy Supply Box": "苔藓供电箱",
    "Nightmare Fuel": "噩梦燃料",
    "Novice Alchemy": "新手炼金术",
    "Novice Cooking": "新手烹饪",
    "Novice Engineering": "新手工程",
    "Occult Damage": "奥术伤害",
    "Occult Damage by 50% for 30 minutes": "奥术伤害提高50%，持续30分钟",
    "Occult Damage every second over 20 seconds": "在20秒内每秒造成奥术伤害",
    "Occult Damage overtime. Once this effect reaches 10 stacks, the target soul will collapse dealing high": "奥术伤害。当这个效果达到10层时，目标灵魂将崩溃，造成高伤害",
    "Old Boot": "旧靴子",
    "Old Rod": "旧杖",
    "Penguin Aviary": "企鹅鸟类饲养场",
    "Picore": "Picore",
    "Pirate Parrot": "海盗鹦鹉",
    "Plated Explorer Boonie": "镀银探险家布尼",
    "Plated Explorer Boots": "镀银探险家靴",
    "Plated Explorer Cuirass": "镀银探险家铁甲",
    "Plated Explorer Gloves": "电镀探险家手套",
    "Plated Explorer Pants": "镀银探险家裤",
    "Plated Explorer Set:": "镀甲探索者套装:",
    "Pringu Emperor": "Pringu皇帝",
    "Pringu Soldier": "Pringu士兵",
    "Prismatic Mattock": "棱镜鹤嘴锄",
    "Pumpkin Spice Latte": "南瓜拿铁",
    "Red Hooded Behest": "红帽命令",
    "Reinforced Stamper": "加强印章",
    "Reinforced Stamper Transfiguration": "加强Stamper变形",
    "Reinforced Wooden Chest": "加固木胸",
    "Relatable Situation": "用情况",
    "Requires [Hell Bindings] x1": "需要[地狱绑定]x1",
    "Rocky Supply Box": "岩石供应箱",
    "Ruinous Soul": "毁灭性的灵魂",
    "Shatterstone Potion": "碎石药水",
    "Shiny Fishing Lure": "闪亮鱼饵",
    "Snapthorn Briar": "刺蒺藜",
    "Soul Canister": "灵魂罐",
    "Soul Grub": "灵魂幼虫",
    "Special Chai Blend": "特调茶",
    "Spineless Tourist": "没有骨气的旅游",
    "Spooky Wood": "令人毛骨悚然的木头",
    "Sporty Supply Box": "运动用品箱",
    "Terragosa": "Terragosa",
    "There is Always A Catch": "总有陷阱",
    "Thunderous Gyroresonator": "雷鸣般的回旋谐振器",
    "Unlock Fishing Pond": "解锁鱼塘",
    "Unlock with an Arcanite Blasting Charge to open": "用一个奥术炸药打开",
    "Waddling Band": "鸭步乐队",
    "Weapon Nature Damage": "武器自然伤害",
    "Web-Threaded Promise": "网络线程预示",
    "Wraithblade Scimitar": "魂刃弯刀",
    "Yellow Cube": "黄色的多维数据集",
    "You cast Cleanse": "你施放了净化",
    "You cast Incendiary Bunny": "你施放了燃烧兔",
    "You cast Polymorph": "你施放了变形术",
    "You cast Wizhard Shell": "你使用了巫师护甲",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "King-Kat": "King-Kat",
    "Ribull": "Ribull",
    "Hoopperoona": "Hoopperoona",
    "Stinglet": "Stinglet",
    "Kasey": "Kasey",
    "kidsmeal": "kidsmeal",
    "Nominae": "Nominae",
    "occultjay": "occultjay",
    "Okko Suga": "Okko Suga",
    "pikacheecks": "pikacheecks",
    "pursuantaunt": "pursuantaunt",
    "rugiesm": "rugiesm",
    "Vitreous Gamba": "Vitreous Gamba",
    "SaWright": "SaWright",
    "✦✧✦✧✦": "✦✧✦✧✦",
    "⚔️⚔️⚔️⚔️⚔️": "⚔️⚔️⚔️⚔️⚔️",
    "★★★★★★": "★★★★★★",
    "★★★★★": "★★★★★",
    "★★★★": "★★★★",
    "★★★": "★★★",
    "★★": "★★",
    "CD": "CD",
    "usajoyrider": "usajoyrider",
    "triplesixstorm": "triplesixstorm",
    "S]": "S]",
    "jefeDeLaR": "jefeDeLaR",
    "johnnydela.": "johnnydela.",
    "kev4217": "kev4217",
    "kgmg": "kgmg",
    "mandlz": "mandlz",
    "maplecream.": "maplecream.",
    "nekosity": "nekosity",
    "RC_Juicebox": "RC_Juicebox",
    "modo diablo 😈": "modo diablo 😈",
    "Jeffrey": "Jeffrey",
    "NombreTortuga": "NombreTortuga",
    "Talar madera o algun tipo de": "Talar madera o algun tipo de",
    "Steven Burton": "Steven Burton",
    "Caulislug": "Caulislug",
    "B1naryV1k1ng": "B1naryV1k1ng",
    "artgor": "artgor",
    "chiasm": "chiasm",
    "forever": "forever",
    "froza": "froza",
    "graham anderson": "graham anderson",
    "tortulily": "tortulily",
    "Sarah": "Sarah",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Trapped Cage x": "被困牢笼 x",
    "❖ Attack Speed: ": "❖ 攻击速度: ",
    "❖ Drop Chance: ": "❖ 掉落几率: ",
    "❖ Critical Chance: ": "❖ 暴击几率: ",
    "❖ Occult Damage: ": "❖ 奥术伤害: ",
    "❖ Might Damage: ": "❖ 力量伤害: ",
    "❖ Nature Damage: ": "❖ 自然伤害: ",
    "❖ Elemental Damage: ": "❖ 元素伤害: ",
    "❖ Deific Damage: ": "❖ 神圣伤害: ",
    "❖ Occult Bonus: ": "❖ 奥术加成: ",
    "❖ Might Bonus: ": "❖ 力量加成: ",
    "❖ Nature Bonus: ": "❖ 自然加成: ",
    "❖ Elemental Bonus: ": "❖ 元素加成: ",
    "❖ Deific Bonus: ": "❖ 神圣加成: ",
    "❖ Max SP: ": "❖ 最大法力值: ",
    "❖ Max Health: ": "❖ 最大生命值: ",
    "❖ Strength: ": "❖ 力量: ",
    "❖ Regeneration: ": "❖ 回复: ",
    "❖ EXP Rate: ": "❖ 经验速率: ",
    "❖ Gathering Bonus: ": "❖ 采集加成: ",
    "❖ Gathering Level: ": "❖ 采集等级: ",
    "❖ Fishing Level: ": "❖ 钓鱼等级: ",
    "[Shortcut: ": "[快捷键: ",
    "Copper Bar": "铜锭",
    "Books Collected : ": "收集的书籍：",
    "\n\n              You are currently missing ": "\n\n              你当前未命中 ",
    "\n              You are currently missing ": "\n              你当前未命中 ",
    "Recipe: ": "配方：",
    "Small Wooden Lockbox x": "小木锁箱 x",
    "Defeated:": "击败：",
    "View your Armory ": "查看你的军械库 ",
    "View your Collection ": "查看您的收藏 ",
    "Copper Key": "铜钥匙",
    "Stock: ": "库存: ",
    "Tin Can": "锡罐",
    "Runic Die": "Runic Die",
    "Silver Ring": "银戒",
    "Regal Broadsword": "豪华阔剑",
    "Grand Archive Key": "大档案钥匙",
    "Cloth Shirt": "布衬衫",
    "Antidote": "解毒剂",
    "Skewed Lizard": "畸形蜥蜴",
    "Stone Mattock": "石头鹤嘴锄",
    "Cloth Slippers": "布拖鞋",
    "Cloth Pants": "布裤子",
    "Cloth Bracelet": "布手镯",
    "Worn Bandana": "旧手帕",
    "Wooden Bow": "木弓",
    "Use: ": "使用: ",
    "Soft Leather Gloves": "软皮手套",
    "On Attack: ": "攻击: ",
    "Equip: ": "装备: ",
    "Wooden Stamper": "木制印章",
    "Pine Boomerang": "松木回旋镖",
    "Net-O-Launcher 3000": "网络启动器 3000",
    "Nephrite-Embedded Ring": "镶软玉戒指",
    "Nephrite": "软玉",
    "Copper Ore": "铜矿石",
    "📄 Log Acquired: ": "📄 日志获取: ",
    "📜 Quest Completed: ": "📜 完成任务: ",
    "Gathered:": "已收集:",
    "Requires: ⛏️ Gathering Level ": "要求: ⛏️ 收集等级 ",
    "Slug Meat": "蛞蝓肉",
    "Topaz": "黄玉",
    "Thorn Binding": "荆棘捆绑",
    "Malachite": "孔雀石",
    "Foliar Blade": "叶刃",
    "Ornate Stamper": "华丽的印章",
    "Open the Bestiary": "打开动物图鉴",
    "Critical Chance": "暴击几率",
    "Low chance to celebrate serizawa festival, increasing damage from all sources by ": "低几率庆祝serizawa节日，增加所有来源的伤害 ",
    "Ornated Stamper": "华丽的印章",
    "Black Belt": "黑带",
    "Select this area to travel to ": "选择这个区域以前往 ",
    "⏱ Time Skipped and gathered ": "⏱ 时间跳过并收集到 ",
    "Requires Novice Alchemy ": "需要新手炼金术 ",
    "Requires Novice Blacksmith ": "要求新手铁匠 ",
    "Requires Novice Engineering ": "要求新手工程学 ",
    "Requires Novice Cooking ": "要求新手烹饪 ",
    "Your attacks have a high chance of summoning lightning to strike your enemies, dealing ": "你的攻击有很高的几率召唤闪电击中你的敌人并造成 ",
    "Last Time: ": "上次: ",
    "Last Wave: ": "上一波: ",
    "Imp Devilfish": "魔鬼鱼",
    "Requires: 🎣 Fishing Level ": "要求: 🎣 钓鱼等级 ",
    "Occult Force": "奥术之力",
    "Might Force": "力量之力",
    "Deific Force": "神圣之力",
    "Nature Force": "自然之力",
    "Elemental Force": "元素之力",
    "Grimjaw Angler": "冷酷的垂钓者",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " /s": " /秒",
    "📜 Quest Completed: Important Notice": "📜 完成任务: 重要通知",
    "ACHIEVEMENT UNLOCKED": "成就已解锁",
    "[Murky Waters]": "[浑水]",
    "(Version History)": "(版本历史)",
    "Mining": "采矿",
    "Settings ⚠️": "设置 ⚠️",
    "Quest": "任务",
    "⚠️ Exports save in a JSON file ⚠️": "⚠️导出保存在JSON文件中⚠️",
    "Disable autosave": "禁用自动保存",
    "Disable custom cursor": "禁用自定义光标",
    "Disable damage on combat log": "禁用战斗日志中的伤害",
    "Disable drops on combat log": "禁用战斗日志中的掉落",
    "Disable EXP on combat log": "禁用战斗日志中的 EXP",
    "Disable floating damage numbers": "禁用浮动伤害数字",
    "Disable numbers on turtle click": "禁用乌龟点击时的数字",
    "Disable particle effects": "禁用粒子效果",
    "Disable penguin recap window on startup": "启动时禁用企鹅回顾窗口",
    "Disable skills on combat log": "在战斗日志中禁用技能",
    "Exports save in a JSON file": "导出保存在 JSON 文件中",
    "Imports a JSON file": "导入 JSON 文件",
    "Mute fighting sounds only": "仅静音战斗声音",
    "Mute game": "游戏静音",
    "Save manually (autosaves every 1 minute)": "手动保存（每 1 分钟自动保存一次）",
    "Switch CTRL interaction for Alt": "将 CTRL 交互切换为 Alt",
    "Wipes all progress": "抹掉所有进度",
    "Equipable - Chest": "可装备 - 胸部",
    "Equipable - Feet": "可装备 - 脚部",
    "Equipable - Hands": "可装备 - 手部",
    "Equipable - Head": "可装备 - 头部",
    "Equipable - Tool": "可装备 - 工具",
    "Equipable - Legs": "可装备 - 腿部",
    "Equipable - Ring": "可装备 - 戒指",
    "Equipable - Trinket": "可装备 - 饰品",
    "Equipable - Weapon": "可装备 - 武器",
    "Consumable - Battle": "消耗品 - 战斗",
    "Consumable - Potion": "消耗品 - 药水",
    "Miscellaneous - Key": "杂项 - 钥匙",
    " minute Cooldown)": " 分钟冷却)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^v ([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)K\/([\d\.]+)K$/,
    /^([\d\.]+)K\/([\d\.]+)M$/,
    /^([\d\.]+)M\/([\d\.]+)B$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^松木回旋镖(.+)$/,
    /^畸形蜥蜴(.+)$/,
    /^成本(.+)$/,
    /^(.+) 经验值！$/,
    /^(.+) 经验值$/,
    /^(.+) 受到$/,
    /^(.+) 力量伤害$/,
    /^(.+) 自然伤害$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\★ ([\d\.]+)K$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\[([\d\.,]+)\%\]$/,
    /^\[([\d\.,]+)\]$/,
    /^\[([\d\.,]+)\/([\d\.,]+)\]$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Obtain (.+) Total Turtle Coins$/, '总计获得 $1 乌龟金币'],
    [/^Increases EXP Gain by (.+) for (.+) minutes$/, '增加 $1 经验增益，持续 $2 分钟'],
    [/^Increases Drop Chance by (.+) for (.+) minutes$/, '增加 $1 掉落几率，持续 $2 分钟'],
    [/^Nature Damage up to a maximum of (.+) damage$/, '自然伤害，最大 $1 点伤害'],
    [/^Elemental Damage by (.+) for (.+) seconds$/, '元素伤害 $1，持续 $2 秒'],
    [/^Elemental Damage by (.+) for (.+) minutes$/, '元素伤害 $1，持续 $2 分钟'],
    [/^Restores (.+) Health$/, '恢复 $1 生命值'],
    [/^Collect (.+) Books$/, '收集 $1 书籍'],
    [/^Complete (.+) Quests$/, '完成 $1 任务'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^and (.+) EXP$/, '和 $1 经验值'],
    [/^You gain (.+) EXP!$/, '您获得 $1 经验值'],
    [/^(.+) heals for$/, '$1 治疗了'],
    [/^(.+) perishes :c$/, '$1 挂掉了 :c'],
    [/^(.+) 💀$/, '$1 💀'],
    [/^(.+) recieves$/, '$1 受到'],
    [/^(.+) gets defeated! You gain (.+) EXP!$/, '$1 被击败了！ 您获得 $2 经验值！'],
    [/^You have (.+) unspent Talent Points$/, '您有 $1 未使用的天赋点'],
    [/^Wave ([\d\.,]+) \- (.+)$/, '波次 $1 \- $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)K HP$/, '$1K 生命值'],
    [/^\[([\d\.]+)\%\] Completion$/, '\[$1\%\] 完成'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+)h$/, '$1 小时'],
    [/^([\d\.,]+)min$/, '$1 分钟'],
    [/^([\d\.,]+)m ([\d\.,]+)s$/, '$1 分钟 $2 秒'],
    [/^([\d\.,]+) Turtle Coins$/, '$1 乌龟金币'],
    [/^([\d\.]+)K Turtle Coins$/, '$1 乌龟金币'],
    [/^([\d\.]+)K Nature Damage$/, '$1 自然伤害'],
    [/^([\d\.,]+) Damage$/, '$1 伤害'],
    [/^([\d\.,]+) Occult Damage$/, '$1 奥术伤害'],
    [/^([\d\.,]+) Might Damage$/, '$1 力量伤害'],
    [/^([\d\.,]+) Elemental Damage$/, '$1 元素伤害'],
    [/^([\d\.,]+) Nature Damage$/, '$1 自然伤害'],
    [/^([\d\.,]+) HP$/, '$1 生命值'],
    [/^([\d\.,]+) ATK$/, '$1 攻击'],
    [/^([\d\.,]+) EXP$/, '$1 经验值'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)\/([\d\.,]+) exp$/, '$1\/$2 经验值'],
    [/^\+(.+) Deific Damage$/, '\+$1 神圣伤害'],
    [/^\+(.+) Elemental Damage$/, '\+$1 元素伤害'],
    [/^\+(.+) Occult Damage$/, '\+$1 奥术伤害'],
    [/^\+(.+) Nature Damage$/, '\+$1 自然伤害'],
    [/^\+(.+) EXP Gain$/, '\+$1 经验增益'],
    [/^\+(.+) Critical Chance$/, '\+$1 暴击几率'],
    [/^\+(.+) Max HP$/, '\+$1 生命值上限'],
    [/^\+(.+) Regeneration$/, '\+$1 回复'],
    [/^\+(.+) Gathering Level$/, '\+$1 采集等级'],
    [/^\+(.+) Might Damage$/, '\+$1 力量伤害'],
    [/^\+(.+) Level$/, '\+$1 等级'],
    [/^\-([\d\.,]+) Haste$/, '\-$1 急速'],
    [/^\-([\d\.,]+) Level$/, '\-$1 等级'],
    [/^\[\+([\d\.,]+) Insight\]$/, '\[\+$1 洞察力\]'],
    [/^\[Level ([\d\.,]+)\]$/, '\[等级 $1\]'],
    [/^\[lvl ([\d\.,]+)\]$/, '\[等级 $1\]'],
    [/^\[\+ ([\d\.,]+)\% Charisma\]$/, '\[\+ $1\% 魅力\]'],
    [/^\[\+ ([\d\.,]+)\% Crit Chance\]$/, '\[\+ $1\% 暴击率\]'],
    [/^\(Max ([\d\.,]+)\)$/, '\(最大 $1\)'],
    [/^Honor: ([\d\.,]+)$/, '荣誉: $1'],
    [/^Reach level ([\d\.,]+)$/, '达到等级 $1'],
    [/^You Have: ([\d\.,]+)$/, '你有: $1'],
    [/^Rank ([\d\.,]+)$/, '段位 $1'],
    [/^lvl ([\d\.,]+)$/, '等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);