/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Requires:": "要求：",
    "RESET": "重置",
    "RESET TALENTS": "重置天赋",
    "resour": "资源",
    "SIGN": "符号",
    "Skills": "技能",
    "SOLD OUT": "已售",
    "Started On:": "开始于：",
    "Super Turtle Idle": "超级乌龟放置",
    "Stern Cricket": "斯特恩板球",
    "Upgrades": "升级",
    "Unlock": "解锁",
    "Upgrades Unlocked": "未解锁升级",
    "Turtle Coins": "乌龟硬币",
    "Travel": "旅行",
    "Township": "乡镇",
    "Total Kills:": "总计击杀：",
    "Total Defeats:": "总计失败次数：",
    "Total Boss Kills:": "总计Boss击杀：",
    "Time Magic": "时间魔法",
    "This action is": "这个动作",
    "Thank you for enrolling in the Super Turtle Adventure program!": "感谢您参加超级乌龟冒险计划！",
    "This is basically a beta test": "这基本上是一个 Beta 测试",
    "Treaties allow the potential of your turtle empire to reach new heights by focusing on specific elements of your kingdom.": "通过专注于王国的特定元素，条约可以让您的乌龟帝国的潜力达到新的高度。",
    "VERSION HISTORY": "版本记录",
    "Wishing Stars": "许愿星",
    "time skipped:": "跳过的时间：",
    "Shop": "商店",
    "Revive": "复活",
    "DELETE": "删除",
    "DROPS": "掉落",
    "Equipment": "装备",
    "Fishing": "钓鱼",
    "Forgotten Series": "被遗忘的系列",
    "Foraging": "觅食",
    "Gold-Tinged Gamba": "金色甘巴",
    "God": "神明",
    "Honor Shop": "荣誉商店",
    "Hallow Forest": "圣徒森林",
    "Import Save": "导入存档",
    "Guildwork": "公会工作",
    "GAME OPTIONS": "游戏选项",
    "Important Notice": "重要通知",
    "Dai-Goran": "戴戈兰",
    "Dayleaf Spice": "黄叶香料",
    "REDEEM": "领取",
    "saved data?": "保存的数据？",
    "SKILLS": "技能",
    "SOON": "很快",
    "Turtle Clicks made:": "乌龟点击：",
    "You obtain": "你得到了",
    "Total Coins Gained:": "获得的金币总数：",
    "Total Playtime:": "总游戏时长：",
    "We are appreciative of your participation in our program. Turtles all across the world will be happy rely on your help and will reward you handsomely for your bravery!": "我们非常感谢您参与我们的计划。 世界各地的海龟都会很高兴依靠你的帮助，并会因为你的勇敢而丰厚地奖励你！",
    "recipes": "配方",
    "We sincerely hope you continue with our program and have a wonderful journey! Here is a welcome gift:": "我们真诚地希望您继续我们的计划并祝您旅途愉快！ 这是一份欢迎礼物：",
    "When the Astral gauge completes, you can get access to the": "当星体量表完成后，您可以访问",
    "When you sign a treaty, a set of": "当您签署条约时，会出现一系列",
    "will be born in honor of your dynasty, alongside increased": "将为您的王朝而诞生，同时增加",
    "You can only switch treaty after an hour.": "您只能在一小时后更改条约。",
    "You obtain": "您获得",
    "You will step down from your position as leader of the turtles, and three": "你将从海龟领袖的位置上退下来，并且三个",
    "Your": "你的",
    "Your hard working Penguin Helpers have been working for you while you weren't online for": "当您不在线时，您辛勤工作的企鹅助手一直在为您工作",
    "⚠ Sell Mode ⚠": "⚠ 出售模式 ⚠",
    "⚠ Lock Mode ⚠": "⚠ 锁定模式 ⚠",
    "⚠ Favorite Mode ⚠": "⚠ 收藏模式 ⚠",
    "❖ Fleming Bite: Applies poison on attack.": "❖ 蜇伤: 在攻击时施放毒药。",
    ", and": ", 并",
    ", you can spend the": "，你可以花费",
    "(click anywhere to close)": "（点击任意地方关闭）",
    "<No Class>": "<无职业>",
    "all": "全部",
    "and": "和",
    "and will": "并将",
    "Armory": "军械库",
    "coins": "金币",
    "exp!": "经验值!",
    "Inventory": "仓库",
    "Jester Turtles Clicked:": "小丑龟点击次数：",
    "Kill": "击杀",
    "MAILBOX": "邮箱",
    "Money": "钱",
    ". Furthermore, treaties can be ranked up to further boost their effects.": "。 此外，可以对条约进行排名，以进一步增强其效果。",
    "\"texto texto texto texto texto texto texto texto texto texto texto\"": "\“文字文字文字文字...",
    "(click outside this window to close)": "（点击该窗口外部即可关闭）",
    "(Full Changelog in the Discord Server)": "（Discord 服务器中的完整更新日志）",
    "[Left Click] Sell One | [Right Click] Sell All": "[左键]出售一个| [右键]全部出售",
    "[Left Click] to Add to the Favorite Tab": "[左键点击]添加到收藏夹选项卡",
    "[Left Click] to Prevent Items From Being Sold": "[左键点击]防止物品被出售",
    "A big thank you for everyone willing to support the development of the game!": "非常感谢大家愿意支持游戏的开发！",
    "A slug so passionate about vegetables that he raised one on its shell. Scientists are in absolute awe.": "一只蛞蝓对蔬菜非常热衷，以至于他在壳上养了一个。 科学家们对此感到绝对敬畏。",
    "Achieve": "达成",
    "Active": "活跃",
    "Active Playtime:": "活跃游戏时长：",
    "Added a bunch of stats for nerds": "为书呆子添加了一堆统计数据",
    "Added and then reworked the achievement system": "添加并重新设计了成就系统",
    "Added Classes and Skills": "添加了课程和技能",
    "Added Crit Chance": "增加暴击几率",
    "Added day cycles and a weather system (not very used for now)": "添加了日循环和天气系统（目前不太使用）",
    "Added Dungeons": "添加了地下城",
    "Added Fishing": "添加了钓鱼",
    "Added Garrisons": "添加驻军",
    "Added import and export save functionality": "新增导入导出保存功能",
    "Added Insight": "增加洞察力",
    "Added Jester Turtles": "添加了小丑龟",
    "Added Mail": "添加邮件",
    "Added Mystery Presents": "添加神秘礼物",
    "Added Penguin Helpers, Penguin power, and other penguin nonsense": "添加了企鹅助手、企鹅力量和其他企鹅废话",
    "Added professions": "新增职业",
    "Added SFX": "添加了特效",
    "Added Stamps": "添加印记",
    "Added the Collection and the Armory": "添加了收藏品和军械库",
    "Added the first two areas (acting as some sort of tutorial)": "添加了前两个区域（充当某种教程）",
    "Added the rpg maingame": "添加了RPG主游戏",
    "Added three new areas, hundreds of items, achievements, yada yada": "添加了三个新区域，数百个项目，成就，yada yada",
    "akerson": "阿克森",
    "All your Talent Points will be refunded.": "您的所有天赋点都将被退还。",
    "Alone No More": "不再孤单",
    "Arcanum Liber": "自由奥秘",
    "are slowly filling up the": "正在慢慢填满",
    "Are you sure you want to delete": "你确定你要删除",
    "Astral gauge": "星体规",
    "Astral level": "星体等级",
    "Banish": "放逐",
    "Beastfallen Series": "野兽堕落者系列",
    "billyawn": "比利翁",
    "Blood Magic": "血魔法",
    "Blue Magic": "蓝色魔法",
    "boons and banes will apply": "好处和坏处都会适用",
    "Camp Construction": "营地建设",
    "Caulislug recieves": "藤条接收",
    "Chai Chai Real Smooth": "柴柴真正光滑",
    "Coins Produced by Clicking:": "点击产生的硬币：",
    "Collection": "收藏",
    "Combat Log": "战斗日志",
    "Combat Statistics": "战斗统计",
    "Common": "常见",
    "Constellations": "星座",
    "Copper Plate": "铜板",
    "Cradle Hills": "摇篮山",
    "Craft": "工艺",
    "Creates:": "创建：",
    "delete all progress of the game": "删除所有游戏进度",
    "DELETE DATA": "删除数据",
    "DELETE SAVEDATA": "删除保存数据",
    "DESCRIPTION": "描述",
    "Dreamwoven Gamba": "织梦甘巴",
    "Dungeons Cleared:": "已清除地下城：",
    "energy": "活力",
    "Exploration": "探索",
    "Export Save": "导出保存",
    "food": "食物",
    "for the next": "为下一个",
    "Garrison": "驻军",
    "Garrison Supplies": "驻军补给品",
    "General": "常规",
    "Gladiator Rank to unlock": "角斗士等级待解锁",
    "Grand Archive": "大档案馆",
    "Granite Grotto": "花岗岩石窟",
    "Have You Seen My Pet": "你看到我的宠物了吗",
    "heinrich1960": "海因里希1960",
    "Heirloom Series": "传家宝系列",
    "horas\n       ": "时间\n",
    "huskymudkipper56": "哈士奇鲈鱼56",
    "in perks to carry over your next legacy.": "获得继承下一个遗产的福利。",
    "In that time, they managed to collect": "在那段时间，他们设法收集",
    "Insight Gained :": "获得的见解：",
    "invisibilia_draconis": "隐形龙",
    "irreversible": "不可逆转的",
    "Item Of The Day": "今日项目",
    "Items Crafted:": "制作的物品：",
    "Items Sold:": "售出物品：",
    "Items Stolen:": "被盗物品：",
    "Last Time: Undefeated": "最后一次：不败",
    "Last Wave: Unattempted": "最后一波：未曾尝试",
    "leave behind all activities, upgrades, coins, resources and exploration levels": "留下所有活动、升级、金币、资源和探索级别",
    "Lesser Alchemical Dust": "小型炼金粉尘",
    "LEVEL": "等级",
    "LOCKED": "锁定",
    "Lost Dojo": "失落的道场",
    "Lumberjack Post": "伐木工人邮报",
    "Lush Passageway": "郁郁葱葱的通道",
    "Made by \"duck\" [drvcx] 🦆": "由“鸭子”[drvcx] 🦆 制作",
    "Make every effort to assist your fellow turtles, as the adventure guild will bestow upon you a unique reward when you fulfill all of their requests in a given area.": "尽一切努力帮助你的海龟同伴，因为当你在特定区域满足他们的所有要求时，冒险公会将给予你独特的奖励。",
    "Masterwork Series": "杰作系列",
    "Metal Workshop": "金属车间",
    "Millionaire Series": "百万富翁系列",
    "Miners Guild Request": "矿工公会请求",
    "Monster Arena": "怪物竞技场",
    "Mystery Presents Opened:": "神秘礼物开启：",
    "Mystery Tickets": "神秘门票",
    "Nameoftheturtle": "乌龟的名字",
    "NEXT ASTRAL LEVEL:": "下一个星体层：",
    "Next Shop Restock": "下一次店铺补货",
    "Next Talent Point:": "下一个天赋点：",
    "Novice Alchemy Recipes": "新手炼金术配方",
    "Novice Blacksmith": "新手铁匠",
    "Novice Blacksmith Recipes": "新手铁匠配方",
    "Novice Cooking Recipes": "新手烹饪配方",
    "Novice Engineering Recipes": "新手工程配方",
    "Oh god what did i do": "天啊我做了什么",
    "On the": "上",
    "Overhauled the graphical aspect of the game... again": "再次彻底修改了游戏的图形方面",
    "Patreon Supporters": "Patreon支持者",
    "penguin": "企鹅",
    "Penguin Assistants": "企鹅助手",
    "Penguin Glacier": "企鹅冰川",
    "Performance": "表现",
    "Pirate Galleon": "海盗帆船",
    "Planetarium": "天文馆",
    "Quests Completed:": "已完成任务：",
    "Epicardo Item": "艾皮卡多物品",
    "Relics": "遗物",
    "Remade everything": "重做一切",
    "Removed max item limit": "删除了最大物品限制",
    "Rename your turtle!": "给你的乌龟重新命名！",
    "Request From a Toad": "蟾蜍的请求",
    "Requires Novice Blacksmith [0]": "需要 新手铁匠 [0]",
    "Research Facility": "研究设施",
    "Revamped the entire graphical aspect of the game": "改进了游戏的整个图形方面",
    "Revered Series": "尊崇系列",
    "Royal Pudding": "皇家布丁",
    "Sawmill Plant": "锯木厂",
    "Slug Meat": "蛞蝓肉",
    "Smelt ore into an ingot of copper.": "将矿石熔炼成铜锭。",
    "Solstice Series": "至日系列",
    "Stamp Weapon": "印记武器",
    "Support the game ❤️": "支持游戏❤️",
    "Support The Game!": "支持游戏！",
    "texto texto texto texto texto texto texto texto texto texto texto": "文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字",
    "This operation will consume one": "这个操作会消耗一个",
    "To My Beloved Friend": "致我挚爱的朋友",
    "Trial of the Mountain": "山之试炼",
    "Uncommon": "罕见",
    "“ I am a prince from Nigeria and a giant idiot spider destroyed shop, give me your money please.": "“我是一位来自尼日利亚的王子，一只巨大的白痴蜘蛛摧毁了商店，请给我你的钱。",
    "“ Muggey, the president of the Chai Association, requests to see the most unusual chai blend of the lands.": "“ 柴协会主席马吉 (Muggey) 要求参观这片土地上最不寻常的柴混合物。",
    "“ My pet Hoopperoona has gone missing. You will recognise her for her eight legs, rocky skin, and the ability to melt steel beams with her saliva.": "“我的宠物胡佩罗娜失踪了。 您会因为她的八条腿、岩石般的皮肤以及用唾液熔化钢梁的能力而认出她。",
    "“ Ribbit Ribbit. Ribbit Ribbit Ribbit Ribbit Ribbit Ribbit Ribbit.  Ribbit Ribbit.": "” 兔子兔子。 兔兔兔兔兔兔兔兔兔兔兔兔兔兔。 兔子 兔子。",
    "“ These scorpions keep blocking the road to our sweet, sweet rocks. Clear the road and well show you our rocky goodness.": "“这些蝎子一直挡住通往我们甜蜜的岩石的道路。 清理道路，我们将向您展示我们岩石般的善良。",
    "“ To complete the registation of the Super Turtle Adventure program, please terrorise the local wildlife.": "“为了完成超级海龟冒险计划的注册，请恐吓当地的野生动物。",
    "\"Life is like a Small Wooden Lockbox.\"": "“生活就像一个小木箱。”",
    "\"Seems inedible, but probably a delicatessen in some parts of France.\"": "“看起来不能吃，但在法国的某些地方可能是熟食店。”",
    "\"This is going to be a terrible night...\"": "“这将是一个可怕的夜晚……”",
    "\"This one is just a rusty sword.\"": "“这只是一把生锈的剑。”",
    "[Possible Contents]": "[可能的内容]",
    "[Tip: Gear levels up automatically after getting multiple copies. Try buying multiple of them] ”": "[提示：获得多个副本后，装备会自动升级。 尝试购买多个]”",
    "[Tip: You can click the turtle to get coins] ”": "【提示：点击乌龟即可获得金币】”",
    "[Tip: You can equip gear by right-clicking it] ”": "【提示：装备右键可以装备】”",
    "[Tip: You can sell items by pressing Control] ”": "【提示：按Control键即可出售物品】”",
    "[Tip: You can switch browser tabs while the game is running] ”": "【提示：游戏运行时可以切换浏览器标签页】”",
    "[Tip: You might want to come later to do certain quests] ”": "[提示：你可能想稍后来完成某些任务]”",
    "{texto texto texto texto texto texto texto texto texto texto texto}": "{文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本文本",
    "❖ ...And More!": "❖ ...还有更多！",
    "❖ Defeat 50 Ribulls": "❖ 击败 50 Ribulls",
    "❖ Defeat 50 Stinglets": "❖ 击败 50 Stinglets",
    "❖ Defeat a bunch of slugs": "❖ 击败一群蛞蝓",
    "❖ Defeat Hoopperoona": "❖ 击败 Hoopperoona",
    "❖ Foliar Blade": "❖ 叶面刀片",
    "❖ Hand over 2500 Turtle Coins": "❖ 交出 2500 海龟币",
    "❖ Malachite": "❖ 孔雀石",
    "❖ Nephrite": "❖ 软玉",
    "❖ Pine Boomerang": "❖ 松木回旋镖",
    "❖ Recipe: Nephrite-Embedded Ring": "❖ 配方：软玉镶嵌戒指",
    "❖ Recipe: Net-o-Launcher 3000": "❖ 配方：网络启动器 3000",
    "❖ Right Click to add to your collection": "❖ 右键单击添加到您的收藏中",
    "❖ Show an unusual tea blend to Muggey": "❖ 向马吉展示一种不寻常的混合茶",
    "❖ Skewed Lizard": "❖ 斜蜥蜴",
    "❖ Thorn Binding": "❖ 荆棘束缚",
    "❖ Wooden Stamper": "❖ 木印模",
    "A cool stick": "很酷的棒子",
    "Access to the Shop": "进入商店",
    "Can be used to summon Hoopperoona": "可以用来召唤Hoopperoona",
    "Collectible": "收藏品",
    "Consumable - Container": "消耗品 - 容器",
    "Experience": "经验",
    "Material": "材料",
    "Miscellaneous": "各种各样的",
    "Miscellaneous - Collectible": "杂项 - 收藏品",
    "Not Collected": "未收集",
    "Objective:": "目标：",
    "Pointy Relic": "尖尖的遗物",
    "Reality Voxel": "现实体素",
    "Masala Chai": "马萨拉柴",
    "Rewards:": "奖励：",
    "Ribbit Ribbit Ribbit": "兔子 兔子 兔子",
    "Sell value:": "售价：",
    "Small Wooden Lockbox": "小木锁箱",
    "Trapped Cage": "困笼",
    "Turtle Voice by \"lily\" [.lilynee] 🐑": "海龟之声 by \"lily\" [.lilynee] 🐑",
    "Unlock Ore Node": "解锁矿石节点",
    "Unlock with a Copper Key to open": "用铜钥匙解锁即可打开",
    "Game Saved": "游戏已保存",
    "(Unique)": "(未装备)",
    "\"A wooden stick shaped like a sword, retaining all the properties of a wooden stick and none of a sword.\"": "“一根形状像剑的木棍，保留了木棍的所有属性，却没有剑的属性。”",
    "COMPLETED": "已完成",
    "Equipable - Weapon": "可装备-武器",
    "Poor": "较差的",
    "Wooden Sword": "木剑",
    "\"The birds are singing, flowers are blooming, on days like these, turtles like you, should have a good day.\"": "“鸟儿在歌唱，花儿在绽放，在这样的日子里，像你这样的乌龟，应该过得愉快。”",
    "Click to cycle through tips": "单击可循环浏览提示",
    "Dedicated Drops": "专属掉落",
    "Enemy": "敌人",
    "No special weather bonuses.": "没有特殊的天气奖励。",
    "Press to fight a meddlesome foe": "按下以对抗爱管闲事的敌人",
    "Press to fight a troublesome foe": "按下以以对抗麻烦的敌人",
    "Press to summon the boss of this area": "按下以召唤该区域的boss",
    "Requires [Trapped Cage] x1": "需要[陷阱牢笼] x1",
    "Sunny Day": "晴天",
    "There is no limit of how many items you can have on the inventory (at least i didnt code one...!)": "库存中可以拥有的物品数量没有限制（至少我没有编码......！）",
    "Weather": "天气",
    "\"A wooden badge commemorating your initiation into adventuring.\"": "“一枚纪念你开始冒险的木制徽章。”",
    "Adventurer Badge": "冒险家徽章",
    "Does nothing ...Or does it?": "什么都不做……是吗?",
    "Equipable - Trinket": "装备-饰品",
    "Make every effort to assist your fellow turtles whenever you go.": "无论你去哪里，都要尽一切努力帮助你的海龟同伴。",
    "We are appreciative of your participation in our program. Turtles all across the world will be happy to rely on your help and in exchange we will reward you handsomely for your bravery!": "我们非常感谢您参加我们的节目。全世界的海龟都很乐意依靠你的帮助，作为交换，我们会对你的勇敢给予丰厚的奖励!",
    "We sincerely hope you continue with our program and have a wonderful journey! Here is your welcome badge:": "我们真诚地希望您继续我们的节目，并有一个美好的旅程!这是你的欢迎徽章:",
    "Wood-Carved Gamba": "木雕甘巴",
    "Collected!": "已收藏！",
    "Press to fight a frightsome foe": "按下可与可怕的敌人战斗",
    "\"Ancient construct that somehow always points out in the same direction.\"": "“古老的建筑，不知何故总是指向同一个方向。”",
    "Guiding Relic": "指引遗物",
    "Mystery Present": "神秘礼物",
    "Mystery Present recieves": "收到神秘礼物",
    "Collected": "已收集",
    "Calm Night": "宁静之夜",
    "\"Its oddly calm tonight.\"": "“今晚出奇地平静。”",
    "permanently": "永久性的",
    "CLICK BOOST!": "点击提升!",
    "Inactive": "非活跃",
    "\"A vital reagent in alchemy and the cauldrons of every self-respecting witch.\"": "“这是炼金术中至关重要的试剂，也是每个有自尊的女巫的坩埚。”",
    "\"One export save a day keeps the data corruption away.\"": "“每天一次导出，避免数据损坏。”",
    "Carefully Wrapped Exported Data": "精心包装的存档数据",
    "Consumable - Miscellaneous": "消耗品-杂项",
    "Frog Leg": "青蛙腿",
    "Open it!": "打开它!",
    "Recognized for their loud croaking sound, numerous noise complaints have been filled wherever they reside. But they never listen...": "它们以响亮的叫声而闻名，无论它们住在哪里，都有无数的噪音投诉。但他们从来不听……",
    "\"...Encased within the shell of the cosmic ovum lay the potential for eternity, awaiting the pivotal moment of hatching, as within resided...\"": "\”…在宇宙之卵的外壳里蕴藏着永恒的潜力，等待着孵化的关键时刻，就像在里面一样……”",
    "\"The fast pass of the adventures.\"": "“冒险的快速通行证。”",
    "(Only works if the current enemy has been defeated more than 100 times)": "(仅当当前敌人被击败超过100次时有效)",
    "Can be used to enter any dungeon": "可以用来进入任何地牢",
    "Dungeon Voucher": "地牢凭证",
    "Epic": "史诗",
    "Perennial Time Egg": "多年生时光蛋",
    "Rare": "稀有",
    "Fast-forwards 6 hours of offline progress": "快进6小时的离线进度",
    "An overgrown arachnid that doesn't seem too up for conversation.": "一只长得太大的蛛形动物，看起来不太愿意说话。",
    "It is said that the poison of these scorpids is more lethal the whiter their tails are. It also kinda looks like a baguette.": "据说，这些蝎子的尾巴越白，毒液就越致命。它看起来也有点像法棍面包。",
    "When you level up, your Strength, Max Health and Regeneration go up.": "当你升级的时候，你的力量，最大生命值和回复会上升。",
    "Area bosses are a great source of experience.": "区域Boss是一个很好的经验来源。",
    "Attributes marked with": "标记的属性",
    "Complete missions to recieve useful rewards in the mail.": "完成任务可以获得邮件中有用的奖励。",
    "Defeating low-level enemies can yield more materials and money at the expense of experience.": "击败低级敌人可以以牺牲经验值为代价获得更多材料和金钱。",
    "Drops marked with a ★ are rare and wont be increased by the Drop Chance stat.": "标有★的掉落是罕见的，并且不会因掉落几率而增加。",
    "Gear marked as \"Unique\" will level up with multiple copies of itself, but only if they have a roman numeral at the side of their name.": "标记为“唯一”的装备将升级为自身的多个副本，但前提是它们的名字旁边有罗马数字。",
    "have unusually high upgrade scaling.": "具有异常高的升级扩展。",
    "Hold Control to sell your items.": "按住Control键出售物品。",
    "Is the enemy too hard? Be sure to check its description and skills to fight accordingly.": "敌人太强悍了吗?一定要检查它的描述和相应的技能来战斗。",
    "The materials found in chests scale with your progress, so be sure to always open them for easy drops.": "在箱子里发现的材料随着你的进度而增加，所以一定要一直打开它们，以便轻松掉落。",
    "You can buy multiple items at once in the shop by pressing Control.": "你可以在商店里按Control键一次购买多种物品。",
    "Upgrade": "升级",
    "Price:": "价格:",
    "\"A fine sword bestowed to the nobility of the turtle kingdom. They say that blood spilled with this edge bleeds blue.\"": "“这是一把赐给龟国贵族的好剑。他们说，从这刀刃流出的血是蓝色的。”",
    "\"A foul-smelling rag for the forehead. Unfortunately, it goes in the head slot.\"": "“用臭布擦额头。不幸的是，它进了头槽。”",
    "\"An ordinary jewelry ring. You can sense good craftsmanship out of it.\"": "“一个普通的珠宝戒指。你可以从中感受到精湛的工艺。”",
    "\"Don't complain, it tastes like chicken.\"": "“别抱怨了，它尝起来像鸡肉。”",
    "\"For the easily-influenced locks.\"": "“对于容易受影响的锁。”",
    "\"It should hold together for a few shots before falling apart entirely.\"": "“在完全散架之前，它应该能撑几下。”",
    "\"May contain beans.\"": "“可能有豆子。”",
    "\"Might be useful in a pinch.\"": "“在紧要关头也许有用。”",
    "\"More effective than nothing whatsoever. Not much more, though.\"": "“总比什么都不做有效。不过不多了。”",
    "\"Seems to not be of your size.\"": "“好像不合你的尺寸。”",
    "\"The key to a massive library recording specifics about the past, present, and future.\"": "“这是打开一个记录过去、现在和未来细节的庞大图书馆的钥匙。”",
    "\"The kind your turtle grandmother would wear.\"": "“就是你的乌龟祖母会穿的那种。”",
    "\"They must at least be resistant if they were able to survive this long.\"": "“如果它们能存活这么久，它们至少是有抵抗力的。”",
    "\"Three thousand years ago, this baby would be considered top-notch engineering, but right now it's better than punching rocks.\"": "“三千年前，这个小东西会被认为是一流的工程，但现在它比打石头要好得多。”",
    "\"Truth is... the game was rigged from the start.\"": "\“真相是……比赛从一开始就被操纵了。”",
    "\"Warm and fuzzy pats are guaranteed by the soft fur of the gloves\"": "“手套柔软的皮毛保证了温暖和毛茸茸的部分。”",
    "Can be used to gather ores and herbs": "可以用来采集矿石和草药吗",
    "Can open small containers": "能打开小容器",
    "Cloth Set:": "布套:",
    "+7% Item Drop Chance": "增加7%物品掉落几率",
    "Might Damage": "力量伤害",
    "Low chance to inflict a royal slash dealing 150-200": "低几率造成150-200点皇家砍伤",
    "Shoot a wooden arrow": "射出一支木箭",
    "Shoot a wooden arrow'": "射出木箭",
    "Permanently increases Turtle Coin reward from clicking by +40": "永久增加点击龟币奖励+40",
    "Permanently unlocks the Grand Archive, gaining insight as you collect books on it": "永久解锁大档案馆，当你收集有关它的书籍时获得洞察力",
    "Prevents enemy-inflicted poisons for 10 minutes": "防止敌人施加的毒药，持续10分钟",
    "Restores 1500-2000 Health": "恢复1500-2000点生命值",
    "Pay 2 Win": "付费2胜",
    "'pat pat pat pat pat pat pat pat pat'": "\"拍，拍，拍，拍，拍\"",
    "\"... all five pieces of the puzzle!\"": "\”…全部五个拼图!\”",
    "\"...........my mone.\"": "\"...........我的局部激素。\”",
    "\"A clump of impure copper ore. For such crude ore to be helpful, it must undergo extensive refinement.\"": "“一堆不纯的铜矿石。要使这种粗矿石有用，它必须经过大量的提炼。”",
    "\"An elvish weapon used by the forest dwelling race known as the Australians.\"": "“一种被称为澳大利亚人的森林居民使用的精灵武器。”",
    "\"An impure variety of jade. Despite that, it still can fetch a good price.\"": "“一种不纯的玉。尽管如此，它仍然可以卖个好价钱。”",
    "\"And this... Is to go further beyond.\"": "\”,这……就是走得更远。”",
    "\"Best I can do is 200 Coins.\"": "“我最多只能出200个金币。”",
    "\"Break a leg.\"": "“祝你好运。”",
    "\"Do you have the client card?\"": "“你有客户卡吗?”\”",
    "\"Everyone is invited c:\"": "“每个人都被邀请了c:\”",
    "\"Feels good man.\"": "“感觉不错，伙计。”",
    "\"First of many.\"": "“这是第一个。”",
    "\"Gacha? Gacha? Gacha!\"": "\“Gacha ?Gacha吗?Gacha !\”",
    "\"Gameplay.\"": "\"游戏。\”",
    "\"Give the cat what he wants.\"": "“给猫它想要的。”",
    "\"Glad we sorted this out one with words alone.\"": "“很高兴我们只用文字就解决了这个问题。”",
    "\"Gotta study them all.\"": "“要把它们都研究一遍。”",
    "\"I could tell you a thing or two.\"": "“我可以告诉你一两件事。”",
    "\"I got enough points for the pot set.\"": "“我得到了足够的分数来做那套锅。”",
    "\"I love the smell of gunpowder in the morning.\"": "“我喜欢早晨的火药味。”",
    "\"I really was ready.\"": "“我真的准备好了。”",
    "\"I saw you peeking.\"": "“我看见你偷看了。”",
    "\"I'm Ready! I'm Ready! I'm Ready! I'm Ready!\"": "\“我准备好了!我准备好了!我准备好了!我准备好了!\”",
    "\"If I can't get them, no one will.\"": "“如果我得不到，就没有人会得到。”",
    "\"It just doesn't feel morally right, right?\"": "“这在道德上是不对的，对吧?”\”",
    "\"It seems she took a liking to you.\"": "“看来她喜欢上你了。”",
    "\"Let your voice be heard.\"": "“让别人听到你的声音。”",
    "\"Literally speaking, that is.\"": "“从字面上讲，就是这样。”",
    "\"Look it up, its a real word.\"": "“查一下，这是一个真实的单词。”",
    "\"Money talk.\"": "\“金钱说话。\”",
    "\"Much wiser through the years.\"": "“随着岁月的流逝，我变得更聪明了。”",
    "\"Not decided yet on what to spend it on.\"": "“还没决定花在什么地方。”",
    "\"Oh yeah it is time.\"": "“哦，是时候了。”",
    "\"Peraphs too ready.\"": "“也许准备得太充分了。”",
    "\"Pluck.\"": "\"勇气。\”",
    "\"Really putting the 'Craft' in TurtleCraft.\"": "“真的是把‘工艺’放进了《turtle lecraft》。”",
    "\"Repaying just a bit of all your kindness.\"": "“回报你的一点好意。”",
    "\"Shattering your expectations.\"": "“打破你的期望。”",
    "\"Smokin' Sexy Style!\"": "“性感得冒烟!”\”",
    "\"Squish Splosh Splooch.\"": "“噗噗噗。”",
    "\"Step 3: Profit.\"": "“第三步:利润。”",
    "\"That's a lotta damage.\"": "“损失可真大。”",
    "\"That's a very disciplined tortuga.\"": "“这是一个非常有纪律的酷刑。”",
    "\"That's not the animal you want to click.\"": "“那不是你想要点击的动物。”",
    "\"The true method of knowledge is experiment.\"": "“获得知识的真正方法是实验。”",
    "\"Threading inbetween life and death.\"": "\"在生与死之间穿梭\"",
    "\"To the shadow realm.\"": "“去影子王国。”",
    "\"Totally uncool, dude.\"": "“太不酷了，伙计。”",
    "\"Turtles can't possibly go to jail.\"": "“乌龟不可能进监狱。”",
    "\"We still need you.\"": "“我们仍然需要你。”",
    "\"What do I like more than materialistic things? Knowledge.\"": "“比起物质的东西，我更喜欢什么?”知识。\”",
    "\"Where will it take me?\"": "“它会带我去哪里?”\”",
    "\"You make even the DEVIL CRY!\"": "“你连魔鬼都哭了!”\”",
    "[Stamps give specific damage bonuses to your weapon or, in rare cases, general ones such as Critical Chance]": "[印记给你的武器特定的伤害加成，或在极少数情况下，一般的，如暴击几率]",
    "★ Set bonus [5]: +250 Max HP": "★套装加成[5]:+250最大HP",
    "❖ Cloth Bracelet": "布料手链",
    "❖ Cloth Pants": "布料裤子",
    "❖ Cloth Shirt": "布料衬衫",
    "❖ Cloth Slippers": "布鞋",
    "❖ Worn Bandana": "戴过的手帕",
    "Bury Me With...": "埋葬我与…",
    "Christmas Is Cancelled": "Christmas Is Cancelled",
    "Critical Thinking": "批判性思维",
    "Cultivated Mind": "培养的心灵",
    "Decked Out": "装饰完毕",
    "Gang Star": "帮派明星",
    "Here Comes The Money": "钱来了",
    "Heroes Never Die!": "英雄不死!",
    "Joker": "小丑",
    "Pawn Star": "典当之星",
    "Power Surge": "电涌",
    "Small Fortune": "小财富",
    "So I Just Need To Let It Run?": "所以我只需要让它运行?",
    "Advanced Adventurer": "先进的冒险家",
    "Applies or rerolls a random stamp to the currently equiped weapon, with a low chance of adding multiple stamp": "在当前装备的武器上应用或滚动一个随机印记，添加多个印记的几率很低",
    "Apprentice Workman": "学徒工人",
    "Assisted Atomisation": "辅助喷雾",
    "Beginner Adventurer": "初学者冒险家",
    "Big Brain": "大脑",
    "Big Dreams": "伟大的梦想",
    "Break a Drake": "打破僵局",
    "Bury Me With...": "把我和……",
    "Christmas Is Cancelled": "圣诞节被取消",
    "Click on a Jester Turtle": "点击一只小丑龟",
    "Completed Book": "完成书",
    "Consumable - Recipe": "消耗品-配方",
    "Critical Thinking": "批判性思维",
    "Cultivated Mind": "培养思维",
    "Deal 100 Critical Hits": "造成100次暴击",
    "Decked Out": "打扮",
    "Destroy 100 Mysterious Presents": "摧毁100个神秘礼物",
    "Equip a full Set of armor": "装备全套护甲",
    "Fight Poison With Poison": "以毒攻毒",
    "Gang Star": "帮派明星",
    "Grateful Representation": "感恩的表示",
    "Here Comes The Money": "钱来了",
    "Heroes Never Die!": "英雄不死!",
    "Ill Take Your Entire Stock": "我要你的全部存货",
    "Joker": "小丑",
    "Learns how to create a Nephrite-Embedded Ring": "学习如何创建一个软玉镶嵌戒指",
    "Learns how to create the Net-o-Launcher 3000": "学习如何创建Net-o-Launcher 3000",
    "Low chance to inflict a royal slash dealing 150-200 '+mightIcon+'Might Damage'": "低几率造成皇家砍伤，造成150-200“+强力剑+可能伤害”",
    "Lucky Streak": "幸运的条纹",
    "Master Adventurer": "主冒险家",
    "Master Of My Craftship": "我的手艺大师",
    "Meat Beater": "肉搅拌器",
    "Missing Book": "丢失的书",
    "Monster Degree": "怪物程度",
    "Monster Obsession": "怪物痴迷",
    "Nature Damage": "自然伤害",
    "New Heights": "一个新的高度",
    "Non Sellable": "不适于销售的",
    "Nothing Like The Present": "没有比现在更好的了",
    "Once in a Blue Moon": "千载难逢",
    "One Punch Turtle": "一拳龟",
    "One way trip": "单程旅行",
    "Oniomaniac Therapy": "Oniomaniac疗法",
    "Pat Pat Pat Pat Pat": "派，派，派，派",
    "Perish 10 times": "死亡 10 次",
    "Play for 10 hours": "玩 10 个小时",
    "Potential Overflow": "潜在的溢出",
    "Quack.": "庸医。",
    "Sell 100K items.": "卖出10万件物品",
    "Sell 10K items.": "卖出1万件物品",
    "Small Fortune": "小财富",
    "So I Just Need To Let It Run?": "所以我只需要让它运行?",
    "Strong Guts": "强大的勇气",
    "Sweet Revenge": "甜蜜的复仇",
    "Tax Fraud": "税务欺诈",
    "Throws a wooden boomerang that deals 260-300": "投掷一个木制回飞镖，造成260-300的伤害",
    "Tortullionaire": "Tortullionaire",
    "Turtle Rabbithole": "乌龟兔子洞",
    "Ultrakill": "Ultrakill",
    "Unpresented Betrayal": "未提出的背叛",
    "Vive la Révolution": "革命万岁",
    "Whatever Did We Do?": "我们做了什么?",
    "You Shall be Known as...": "你将被称为……",
    "\"The stinger of a scorpid. Small traces of poison can be seen on the tip.\"": "“蝎子的毒刺。在尖端可以看到少量的毒药痕迹。”",
    "[Stamps]": "[印记]",
    "Elemental Force I": "元素之力I",
    "Learned!": "学会了!",
    "Nature Force I": "自然之力I",
    "White Stinger": "白毒刺",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Ribull": "Ribull",
    "Hoopperoona": "Hoopperoona",
    "Stinglet": "Stinglet",
    "Kasey": "Kasey",
    "kidsmeal": "kidsmeal",
    "Nominae": "Nominae",
    "occultjay": "occultjay",
    "Okko Suga": "Okko Suga",
    "pikacheecks": "pikacheecks",
    "pursuantaunt": "pursuantaunt",
    "rugiesm": "rugiesm",
    "Vitreous Gamba": "Vitreous Gamba",
    "SaWright": "SaWright",
    "✦✧✦✧✦": "✦✧✦✧✦",
    "⚔️⚔️⚔️⚔️⚔️": "⚔️⚔️⚔️⚔️⚔️",
    "★★★★★★": "★★★★★★",
    "★★★★★": "★★★★★",
    "★★★★": "★★★★",
    "★★★": "★★★",
    "★★": "★★",
    "CD": "CD",
    "usajoyrider": "usajoyrider",
    "triplesixstorm": "triplesixstorm",
    "S]": "S]",
    "jefeDeLaR": "jefeDeLaR",
    "johnnydela.": "johnnydela.",
    "kev4217": "kev4217",
    "kgmg": "kgmg",
    "mandlz": "mandlz",
    "maplecream.": "maplecream.",
    "nekosity": "nekosity",
    "RC_Juicebox": "RC_Juicebox",
    "modo diablo 😈": "modo diablo 😈",
    "Jeffrey": "Jeffrey",
    "NombreTortuga": "NombreTortuga",
    "Talar madera o algun tipo de": "Talar madera o algun tipo de",
    "Steven Burton": "Steven Burton",
    "Caulislug": "Caulislug",
    "B1naryV1k1ng": "B1naryV1k1ng",
    "artgor": "artgor",
    "chiasm": "chiasm",
    "forever": "forever",
    "froza": "froza",
    "graham anderson": "graham anderson",
    "tortulily": "tortulily",
    "Sarah": "Sarah",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Trapped Cage x": "被困牢笼 x",
    "❖ Attack Speed: ": "❖ 攻击速度: ",
    "❖ Drop Chance: ": "❖ 掉落率: ",
    "❖ Critical Chance: ": "❖ 暴击率: ",
    "❖ Occult Damage: ": "❖ 奥术伤害: ",
    "❖ Might Damage: ": "❖ 力量伤害: ",
    "❖ Nature Damage: ": "❖ 自然伤害: ",
    "❖ Elemental Damage: ": "❖ 元素伤害: ",
    "❖ Deific Damage: ": "❖ 神圣伤害: ",
    "❖ Occult Bonus: ": "❖ 奥术加成: ",
    "❖ Might Bonus: ": "❖ 力量加成: ",
    "❖ Nature Bonus: ": "❖ 自然加成: ",
    "❖ Elemental Bonus: ": "❖ 元素加成: ",
    "❖ Deific Bonus: ": "❖ 神圣加成: ",
    "❖ Max SP: ": "❖ 最大法力值: ",
    "❖ Max Health: ": "❖ 最大生命值: ",
    "❖ Strength: ": "❖ 力量: ",
    "❖ Regeneration: ": "❖ 回复: ",
    "❖ EXP Rate: ": "❖ 经验速率: ",
    "❖ Gathering Bonus: ": "❖ 采集加成: ",
    "❖ Gathering Level: ": "❖ 采集等级: ",
    "❖ Fishing Level: ": "❖ 钓鱼等级: ",
    "[Shortcut: ": "[快捷键: ",
    "Copper Bar": "铜锭",
    "Books Collected : ": "收集的书籍：",
    "\n\n              You are currently missing ": "\n\n              你当前未命中 ",
    "\n              You are currently missing ": "\n              你当前未命中 ",
    "Recipe: ": "配方：",
    "Small Wooden Lockbox x": "小木锁箱 x",
    "Defeated:": "击败：",
    "View your Armory ": "查看你的军械库 ",
    "View your Collection ": "查看您的收藏 ",
    "Copper Key": "铜钥匙",
    "Stock: ": "库存: ",
    "Tin Can": "锡罐",
    "Runic Die": "Runic Die",
    "Silver Ring": "银戒",
    "Regal Broadsword": "豪华阔剑",
    "Grand Archive Key": "大档案钥匙",
    "Cloth Shirt": "布衬衫",
    "Antidote": "解毒剂",
    "Skewed Lizard": "畸形蜥蜴",
    "Stone Mattock": "石头鹤嘴锄",
    "Cloth Slippers": "布拖鞋",
    "Cloth Pants": "布裤子",
    "Cloth Bracelet": "布手镯",
    "Worn Bandana": "旧手帕",
    "Wooden Bow": "木弓",
    "Use: ": "使用: ",
    "Soft Leather Gloves": "软皮手套",
    "On Attack: ": "攻击: ",
    "Equip: ": "装备: ",
    "Wooden Stamper": "木制印记",
    "Pine Boomerang": "松木回旋镖",
    "Net-O-Launcher 3000": "网络启动器 3000",
    "Nephrite-Embedded Ring": "镶软玉戒指",
    "Nephrite": "软玉",
    "Copper Ore": "铜矿石",
    "📄 Log Acquired: ": "📄 日志获取: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " /s": " /秒",
    "📜 Quest Completed: Important Notice": "📜任务完成: 重要通知",
    "ACHIEVEMENT UNLOCKED": "成就已解锁",
    "[Murky Waters]": "[浑水]",
    "(Version History)": "(版本历史)",
    "Mining": "采矿",
    "Settings ⚠️": "设置 ⚠️",
    "Quest": "任务",
    "⚠️ Exports save in a JSON file ⚠️": "⚠️导出保存在JSON文件中⚠️",
    "Disable autosave": "禁用自动保存",
    "Disable custom cursor": "禁用自定义光标",
    "Disable damage on combat log": "禁用战斗日志中的伤害",
    "Disable drops on combat log": "禁用战斗日志中的掉落",
    "Disable EXP on combat log": "禁用战斗日志中的 EXP",
    "Disable floating damage numbers": "禁用浮动伤害数字",
    "Disable numbers on turtle click": "禁用乌龟点击时的数字",
    "Disable particle effects": "禁用粒子效果",
    "Disable penguin recap window on startup": "启动时禁用企鹅回顾窗口",
    "Disable skills on combat log": "在战斗日志中禁用技能",
    "Exports save in a JSON file": "导出保存在 JSON 文件中",
    "Imports a JSON file": "导入 JSON 文件",
    "Mute fighting sounds only": "仅静音战斗声音",
    "Mute game": "游戏静音",
    "Save manually (autosaves every 1 minute)": "手动保存（每 1 分钟自动保存一次）",
    "Switch CTRL interaction for Alt": "将 CTRL 交互切换为 Alt",
    "Wipes all progress": "抹掉所有进度",
    "Equipable - Chest": "可装备 - 胸部",
    "Equipable - Feet": "可装备 - 脚部",
    "Equipable - Hands": "可装备 - 手部",
    "Equipable - Head": "可装备 - 头部",
    "Equipable - Tool": "可装备 - 工具",
    "Equipable - Legs": "可装备 - 腿部",
    "Equipable - Ring": "可装备 - 戒指",
    "Equipable - Trinket": "可装备 - 饰品",
    "Equipable - Weapon": "可装备 - 武器",
    "Consumable - Battle": "消耗品 - 战斗",
    "Consumable - Potion": "消耗品 - 药水",
    "Miscellaneous - Key": "杂项 - 钥匙",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^v ([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)K\/([\d\.]+)K$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^(.+) 经验值！$/,
    /^(.+) 受到$/,
    /^(.+) 自然伤害$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\★ ([\d\.]+)K$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\[([\d\.,]+)\%\]$/,
    /^\[([\d\.,]+)\]$/,
    /^\[([\d\.,]+)\/([\d\.,]+)\]$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Obtain (.+) Total Turtle Coins$/, '总计获得 $1 乌龟金币'],
    [/^Collect (.+) Books$/, '收集 $1 书籍'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You gain (.+) EXP!$/, '您获得 $1 经验值'],
    [/^(.+) heals for$/, '$1 治疗了'],
    [/^(.+) perishes :c$/, '$1 挂掉了 :c'],
    [/^(.+) 💀$/, '$1 💀'],
    [/^(.+) recieves$/, '$1 受到'],
    [/^(.+) gets defeated! You gain (.+) EXP!$/, '$1 被击败了！ 您获得 $2 经验值！'],
    [/^You have (.+) unspent Talent Points$/, '您有 $1 未使用的天赋点'],
    [/^Wave ([\d\.,]+) \- (.+)$/, '波次 $1 \- $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)K HP$/, '$1K 生命值'],
    [/^\[([\d\.]+)\%\] Completion$/, '\[$1\%\] 完成'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+)h$/, '$1 小时'],
    [/^([\d\.,]+)min$/, '$1 分钟'],
    [/^([\d\.,]+)m ([\d\.,]+)s$/, '$1 分钟 $2 秒'],
    [/^([\d\.,]+) Turtle Coins$/, '$1 乌龟金币'],
    [/^([\d\.]+)K Turtle Coins$/, '$1 乌龟金币'],
    [/^([\d\.,]+) Damage$/, '$1 伤害'],
    [/^([\d\.,]+) Might Damage$/, '$1 力量伤害'],
    [/^([\d\.,]+) Nature Damage$/, '$1 自然伤害'],
    [/^([\d\.,]+) HP$/, '$1 生命值'],
    [/^([\d\.,]+) ATK$/, '$1 攻击'],
    [/^([\d\.,]+) EXP$/, '$1 经验值'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)\/([\d\.,]+) exp$/, '$1\/$2 经验值'],
    [/^\+([\d\.,]+) Nature Damage$/, '\+$1 自然伤害'],
    [/^\+([\d\.,]+) Max HP$/, '\+$1 生命值上限'],
    [/^\+([\d\.,]+) Regeneration$/, '\+$1 回复'],
    [/^\+([\d\.,]+) Gathering Level$/, '\+$1 采集等级'],
    [/^\+([\d\.,]+) Might Damage$/, '\+$1 武力伤害'],
    [/^\+([\d\.,]+) Level$/, '\+$1 等级'],
    [/^\-([\d\.,]+) Level$/, '\-$1 等级'],
    [/^\[\+([\d\.,]+) Insight\]$/, '\[\+$1 洞察力\]'],
    [/^\[Level ([\d\.,]+)\]$/, '\[等级 $1\]'],
    [/^\[lvl ([\d\.,]+)\]$/, '\[等级 $1\]'],
    [/^\[\+ ([\d\.,]+)\% Charisma\]$/, '\[\+ $1\% 魅力\]'],
    [/^\[\+ ([\d\.,]+)\% Crit Chance\]$/, '\[\+ $1\% 暴击率\]'],
    [/^\(Max ([\d\.,]+)\)$/, '\(最大 $1\)'],
    [/^Honor: ([\d\.,]+)$/, '荣誉: $1'],
    [/^Reach level ([\d\.,]+)$/, '达到等级 $1'],
    [/^Rank ([\d\.,]+)$/, '段位 $1'],
    [/^lvl ([\d\.,]+)$/, '等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);